/**
 * YQArch command registry — complete commands from the official YQArch PDF manual (24 pages)
 *
 * Each command maps to a real YQArch LISP function (e.g., yq_wall, yq_hole_door).
 * The LISP bridge calls these directly via (c:yq_functionname).
 */

export interface CommandDef {
  name: string;        // LISP function name (lowercase, e.g. "yq_wall")
  shortcut: string;    // YQArch shortcut key (e.g. "ww")
  description: string; // English description
  importance: number;  // 1-5 stars
}

export interface Category {
  id: string;
  label: string;
  description: string;
  commands: CommandDef[];
}

export const categories: Category[] = [
  // ─── SYSTEM SETUP ───────────────────────────────────────────────────
  {
    id: "system_setup",
    label: "System Setup",
    description: "User preferences, toolbars, language, units, scale, drawing frame, help",
    commands: [
      { name: "yq_sys", shortcut: "YQSYS", description: "User Preferences", importance: 1 },
      { name: "yq_commandpandect", shortcut: "YQ", description: "YQArch Command Pandect", importance: 1 },
      { name: "yq_tba", shortcut: "TBA", description: "Show YQArch Toolbars", importance: 1 },
      { name: "yq_tbaf", shortcut: "TBAF", description: "Hide YQArch Toolbars", importance: 1 },
      { name: "yq_user", shortcut: "YQUSER", description: "Select Current User", importance: 1 },
      { name: "yq_lang", shortcut: "YQLANG", description: "Select Language", importance: 1 },
      { name: "yq_units", shortcut: "YQUNITS", description: "Set Default Units", importance: 1 },
      { name: "yq_menu", shortcut: "YQMENU", description: "Reload YQArch Menu", importance: 1 },
      { name: "yq_scale", shortcut: "SD", description: "Set Drawing/System Scale", importance: 1 },
      { name: "yq_drawingframe", shortcut: "TK", description: "Drawing Frame A0-A4", importance: 1 },
      { name: "yq_help", shortcut: "YQHELP", description: "YQArch Help", importance: 1 },
    ],
  },

  // ─── PLANE WALL/COLUMN ─────────────────────────────────────────────
  {
    id: "plane_wall_column",
    label: "Plane Wall/Column",
    description: "Axis lines, grid axes, walls, columns, wall editing",
    commands: [
      { name: "yq_axisline", shortcut: "AX", description: "Draw Axis Line", importance: 3 },
      { name: "yq_gridaxis", shortcut: "ZXW", description: "Draw Grid Axis", importance: 3 },
      { name: "yq_wall", shortcut: "WW", description: "Draw Wall", importance: 5 },
      { name: "yq_trim_fix_wall", shortcut: "TW", description: "Wall Scissor/Trim", importance: 5 },
      { name: "yq_wall_chgthk", shortcut: "WWT", description: "Change Wall Thickness", importance: 4 },
      { name: "yq_line2wall", shortcut: "XWW", description: "Axis Lines of Walls / Convert lines to walls", importance: 3 },
      { name: "yq_wall_offset", shortcut: "WWO", description: "Wall Offsetting", importance: 3 },
      { name: "yq_rebuilt_wall_axis", shortcut: "WWA", description: "Rebuilt Wall Axis", importance: 2 },
      { name: "yq_fill_walls", shortcut: "WWF", description: "Fill in Walls/Columns", importance: 3 },
      { name: "yq_r_column", shortcut: "ZZR", description: "Rectangular Column", importance: 4 },
      { name: "yq_o_column", shortcut: "ZZC", description: "O Shape Column / Circular", importance: 4 },
      { name: "yq_l_column", shortcut: "ZZL", description: "L Shape Column", importance: 3 },
      { name: "yq_t_column", shortcut: "ZZT", description: "T Shape Column", importance: 3 },
      { name: "yq_c_column", shortcut: "ZZX", description: "+ Shape Column / Cross", importance: 3 },
      { name: "yq_axis_column", shortcut: "ZZBZ", description: "Arrange Columns on axes", importance: 2 },
      { name: "yq_convert_column", shortcut: "XXZZ", description: "Convert to Column", importance: 2 },
      { name: "yq_fill_column", shortcut: "ZZF", description: "Fill in Columns", importance: 2 },
      { name: "yq_erase_wall", shortcut: "EW", description: "Delete Win/Dr/Wall/Col", importance: 4 },
    ],
  },

  // ─── PLANE WINDOW/DOOR ─────────────────────────────────────────────
  {
    id: "plane_window_door",
    label: "Plane Window/Door",
    description: "Doors and windows on walls, free placement, pocket doors, parametric windows, corner windows",
    commands: [
      { name: "yq_hole_door", shortcut: "AD", description: "Open Door on wall", importance: 5 },
      { name: "yq_door", shortcut: "AD2", description: "Draw a Door free", importance: 3 },
      { name: "yq_hole_win", shortcut: "AW", description: "Open Window on wall", importance: 5 },
      { name: "yq_win", shortcut: "AW2", description: "Draw a Window free", importance: 3 },
      { name: "yq_windoor_replace", shortcut: "TD", description: "Replace Window/Door", importance: 4 },
      { name: "yq_hole", shortcut: "HO", description: "Auto Open Hole", importance: 2 },
      { name: "yq_hole_pocketdoor", shortcut: "ADT", description: "Open Pocket Door", importance: 4 },
      { name: "yq_pocketdoor", shortcut: "ADT2", description: "Draw a Pocket Door", importance: 3 },
      { name: "yq_replace_pocketdoor", shortcut: "TDD", description: "Replace by Pocket Door", importance: 3 },
      { name: "yq_hole_window", shortcut: "WD", description: "Open Param Window", importance: 5 },
      { name: "yq_window", shortcut: "WD2", description: "Draw a Param Window", importance: 3 },
      { name: "yq_replace_paramwindow", shortcut: "TDW", description: "Replace by Param Window", importance: 3 },
      { name: "yq_hole_cornerwindow", shortcut: "WDZ", description: "Open Corner Window", importance: 4 },
      { name: "yq_replace_cornerwindow", shortcut: "TDZ", description: "Replace Corner Window", importance: 3 },
      { name: "yq_doorsill_manager", shortcut: "MKX", description: "Doorsill Manager", importance: 2 },
      { name: "yq_dooropening_manager", shortcut: "MDX", description: "Door Opening Manager", importance: 2 },
      { name: "yq_lines2windows", shortcut: "XWD", description: "Lines to Windows", importance: 2 },
      { name: "yq_width_windoor", shortcut: "CW", description: "Change Window/Door Width", importance: 4 },
      { name: "yq_move_windoor", shortcut: "VW", description: "Move Window/Door", importance: 4 },
      { name: "yq_repair", shortcut: "XF", description: "Repair Win/Door/Column", importance: 4 },
      { name: "yq_move_repair", shortcut: "VX", description: "Move and Fix", importance: 3 },
      { name: "yq_copy_repair", shortcut: "CK", description: "Copy and Fix", importance: 3 },
      { name: "yq_mirror_repair", shortcut: "RRX", description: "Mirror and Fix", importance: 3 },
      { name: "yq_window_serial", shortcut: "WBH", description: "Window Serial Number", importance: 1 },
    ],
  },

  // ─── BUILDING COMPONENTS ───────────────────────────────────────────
  {
    id: "building_components",
    label: "Building Components",
    description: "Escalators, staircases, elevators, door/window elevations and sections, curtain walls, banisters",
    commands: [
      { name: "yq_component_index", shortcut: "GJ", description: "Index of Components", importance: 2 },
      { name: "yq_escalator", shortcut: "LTF", description: "Plan/Elev Escalator", importance: 4 },
      { name: "yq_staircase_plan", shortcut: "LTJ", description: "Plan of Staircase", importance: 4 },
      { name: "yq_arcstair_plan", shortcut: "ITA", description: "Plan of Arch Staircase", importance: 3 },
      { name: "yq_lift_plan", shortcut: "DTJ", description: "Plan of Elevator", importance: 3 },
      { name: "yq_door_elevation", shortcut: "ADE", description: "Elevation of Door", importance: 3 },
      { name: "yq_door_section", shortcut: "ADS", description: "Section of Door", importance: 3 },
      { name: "yq_baywin_section", shortcut: "WTS", description: "Section of Bay Window", importance: 2 },
      { name: "yq_window_elevation", shortcut: "WDE", description: "Elevation of Window", importance: 3 },
      { name: "yq_window_section", shortcut: "WDS", description: "Section of Window", importance: 3 },
      { name: "yq_shutter", shortcut: "BY", description: "Elev/Sect of Shutter", importance: 2 },
      { name: "yq_curtainwall_glass", shortcut: "MBL", description: "Curtain Wall Glass", importance: 3 },
      { name: "yq_lines2windowelev", shortcut: "WDD", description: "Lines to Window Elevation", importance: 2 },
      { name: "yq_sn2windowelev", shortcut: "T2W", description: "SN to Window Elevation", importance: 2 },
      { name: "yq_curtainwall", shortcut: "MQ", description: "Elevation of Curtain Wall", importance: 3 },
      { name: "yq_glass_partition", shortcut: "MQS", description: "Section of Partition", importance: 3 },
      { name: "yq_banister", shortcut: "LG", description: "Elevation Banister", importance: 3 },
      { name: "yq_staircase_section", shortcut: "LTP", description: "Section of Staircase", importance: 4 },
      { name: "yq_steps_section", shortcut: "LXTB", description: "Section of Steps", importance: 2 },
      { name: "yq_waterproof_section", shortcut: "FSC", description: "Section of Waterproof", importance: 2 },
      { name: "yq_stucco_section", shortcut: "FN", description: "Section of Stucco", importance: 2 },
    ],
  },

  // ─── DECORATION ────────────────────────────────────────────────────
  {
    id: "decoration",
    label: "Decoration",
    description: "Furniture, bathroom, cupboards, flooring, lighting, pipes, indoor elevation",
    commands: [
      { name: "yq_deco_index", shortcut: "ZS", description: "Index of Decoration Components", importance: 2 },
      { name: "yq_autofurniture", shortcut: "IJ", description: "Auto Arrange Furniture", importance: 5 },
      { name: "yq_arrangewc", shortcut: "WC", description: "Arrange WC/Shower", importance: 5 },
      { name: "yq_chest", shortcut: "YG", description: "Plan of Chest", importance: 2 },
      { name: "yq_curtain_plan", shortcut: "CLP", description: "Plan of Curtain", importance: 2 },
      { name: "yq_plaster_string", shortcut: "SGX", description: "Plan of Plaster String", importance: 2 },
      { name: "yq_cupboard", shortcut: "GZ", description: "Plan of Cupboard", importance: 3 },
      { name: "yq_cupboard_elev", shortcut: "GZE", description: "Elevation of Cupboard", importance: 2 },
      { name: "yq_stonetile", shortcut: "STB", description: "Section of Stone Tile", importance: 3 },
      { name: "yq_woodframe", shortcut: "MF", description: "Section of Wooden Frame", importance: 2 },
      { name: "yq_boards_array", shortcut: "CBZ", description: "Boards Array", importance: 2 },
      { name: "yq_blockboard", shortcut: "MGB", description: "Section of Blockboard", importance: 1 },
      { name: "yq_plywood", shortcut: "IB", description: "Section of Plywood", importance: 1 },
      { name: "yq_woodflooring", shortcut: "MDB", description: "Section of Wood Flooring", importance: 2 },
      { name: "yq_gypsumboard", shortcut: "SGB", description: "Section of Gypsum Board", importance: 3 },
      { name: "yq_lighttrough", shortcut: "THDC", description: "Section Light Trough", importance: 2 },
      { name: "yq_partitionwall", shortcut: "GQ", description: "Partition Wall", importance: 3 },
      { name: "yq_glass_section", shortcut: "BL", description: "Section of Glass", importance: 2 },
      { name: "yq_formedsteel", shortcut: "XG", description: "Formed Steel", importance: 1 },
      { name: "yq_ironframe", shortcut: "IGJ", description: "Section Iron Frame", importance: 1 },
      { name: "yq_insulation", shortcut: "BWM", description: "Cotton Insulation", importance: 1 },
      { name: "yq_welding", shortcut: "HF", description: "Welding Line", importance: 1 },
      { name: "yq_hose", shortcut: "RG", description: "Draw Hose", importance: 1 },
      { name: "yq_pipe", shortcut: "GX", description: "Draw Pipe", importance: 1 },
      { name: "yq_hole_board", shortcut: "KD", description: "Hole on Board", importance: 1 },
      { name: "yq_cylinder_shadow", shortcut: "YZX", description: "Cylinder Shadow", importance: 1 },
      { name: "yq_backbolt", shortcut: "BSK", description: "Back-Bolt Hole", importance: 1 },
      { name: "yq_autolamps", shortcut: "DJ", description: "Arrange Lamps", importance: 2 },
      { name: "yq_random_spread", shortcut: "MTX", description: "Random Spread", importance: 1 },
      { name: "yq_indoor_elevation", shortcut: "IM", description: "Indoor Elevation", importance: 3 },
    ],
  },

  // ─── ARCHITECTURAL SYMBOLS ─────────────────────────────────────────
  {
    id: "architectural_symbols",
    label: "Architectural Symbols",
    description: "Axis symbols, elevation markers, section planes, slope, disconnection, arrows",
    commands: [
      { name: "yq_symbol_index", shortcut: "FH", description: "Index of Symbols", importance: 2 },
      { name: "yq_auto_axis_dim", shortcut: "AZH", description: "Arrange Axis Symbols", importance: 4 },
      { name: "yq_symbol_axis_c", shortcut: "ZH", description: "Draw Axis Symbols", importance: 4 },
      { name: "yq_geodesic", shortcut: "ZB", description: "Geodesic Coordinates", importance: 2 },
      { name: "yq_designed_elevation", shortcut: "BG", description: "Designed Elevation", importance: 4 },
      { name: "yq_contour_elevation", shortcut: "XBG", description: "Contour Elevation", importance: 3 },
      { name: "yq_section_plane", shortcut: "PQF", description: "Section Plane Symbols", importance: 3 },
      { name: "yq_symbol_sectioncutter", shortcut: "DMF", description: "Section Cutter Symbols", importance: 3 },
      { name: "yq_slope", shortcut: "PD", description: "Slope Symbol", importance: 2 },
      { name: "yq_disconnection", shortcut: "ZX", description: "Disconnection Line", importance: 2 },
      { name: "yq_pipe_cutting", shortcut: "GPX", description: "Pipe Cutting Symbol", importance: 1 },
      { name: "yq_symmetry_axis", shortcut: "DCZ", description: "Symmetry Axis", importance: 2 },
      { name: "yq_central_line", shortcut: "ZXX", description: "Central Line", importance: 2 },
      { name: "yq_wire_surround", shortcut: "ACC", description: "Wire Surround", importance: 1 },
      { name: "yq_erase_surround", shortcut: "ECC", description: "Erase Surround", importance: 1 },
      { name: "yq_bent_arrow", shortcut: "AAW", description: "Bent Arrow", importance: 2 },
      { name: "yq_entrancearrow", shortcut: "AAE", description: "Entrance Arrow", importance: 2 },
    ],
  },

  // ─── INDEX SYMBOLS ─────────────────────────────────────────────────
  {
    id: "index_symbols",
    label: "Index Symbols",
    description: "Section symbols, elevation indexers, detail symbols, leaders, drawing title",
    commands: [
      { name: "yq_indexer_index", shortcut: "SY", description: "Index of Indexers", importance: 2 },
      { name: "yq_section_sym1", shortcut: "SY1", description: "Section Symbol 1", importance: 3 },
      { name: "yq_section_sym2", shortcut: "SY2", description: "Section Symbol 2", importance: 3 },
      { name: "yq_section_sym3", shortcut: "SY3", description: "Section Symbol 3", importance: 3 },
      { name: "yq_elev_indexer_4in1", shortcut: "I0", description: "Elevation Indexer 4in1", importance: 3 },
      { name: "yq_elev_indexer1", shortcut: "I1", description: "Elevation Indexer 1", importance: 3 },
      { name: "yq_elev_indexer2", shortcut: "I2", description: "Elevation Indexer 2", importance: 3 },
      { name: "yq_elev_indexer3", shortcut: "I3", description: "Elevation Indexer 3", importance: 3 },
      { name: "yq_elev_indexer4", shortcut: "I4", description: "Elevation Indexer 4", importance: 3 },
      { name: "yq_detail_sym1", shortcut: "XT1", description: "Detail Drawing Symbol 1", importance: 3 },
      { name: "yq_detail_sym2", shortcut: "XT2", description: "Detail Drawing Symbol 2", importance: 3 },
      { name: "yq_indexer1", shortcut: "S1", description: "Indexer 1", importance: 2 },
      { name: "yq_indexer2", shortcut: "S2", description: "Indexer 2", importance: 2 },
      { name: "yq_indexer3", shortcut: "S3", description: "Indexer 3", importance: 2 },
      { name: "yq_indexer4", shortcut: "S4", description: "Indexer 4", importance: 2 },
      { name: "yq_indexer5", shortcut: "S5", description: "Indexer 5", importance: 2 },
      { name: "yq_indexer6", shortcut: "S6", description: "Indexer 6", importance: 2 },
      { name: "yq_indexer7", shortcut: "S7", description: "Indexer 7", importance: 2 },
      { name: "yq_indexer8", shortcut: "S8", description: "Indexer 8", importance: 2 },
      { name: "yq_indexer9", shortcut: "S9", description: "Indexer 9", importance: 2 },
      { name: "yq_leader", shortcut: "AAX", description: "Arrow Leader", importance: 4 },
      { name: "yq_multi_leader", shortcut: "AAXX", description: "Multi-Point Leader", importance: 3 },
      { name: "yq_vert_leader", shortcut: "AAYY", description: "Vertical Multi-point Leader", importance: 2 },
      { name: "yq_add_leader_vertex", shortcut: "AAV", description: "Add/Remove Leader Vertex", importance: 2 },
      { name: "yq_add_leader_arrows", shortcut: "AAJ", description: "Add Leader Arrows", importance: 2 },
      { name: "yq_drawingtitle", shortcut: "BT", description: "Decoration Drawing Title", importance: 3 },
    ],
  },

  // ─── STATISTICS TOOLS ──────────────────────────────────────────────
  {
    id: "statistics_tools",
    label: "Statistics Tools",
    description: "Filtered select, serial numbers, tables, area calculations, material lists",
    commands: [
      { name: "yq_stat_index", shortcut: "TJ", description: "Index of Statistics", importance: 1 },
      { name: "yq_filtered_select", shortcut: "SS", description: "Easy Filtered Select", importance: 2 },
      { name: "yq_auto_serial", shortcut: "ABH", description: "Auto Serial Number", importance: 1 },
      { name: "yq_empty_table", shortcut: "KBG", description: "Make Empty Table", importance: 1 },
      { name: "yq_table_align", shortcut: "BGZ", description: "Table Texts Aligning", importance: 1 },
      { name: "yq_cell_area", shortcut: "TMJ", description: "Cell Area by Text", importance: 1 },
      { name: "yq_text2cell", shortcut: "T2E", description: "Text to Cell Editor", importance: 1 },
      { name: "yq_text2table", shortcut: "ZBG", description: "Text to Table", importance: 1 },
      { name: "yq_windoor_list", shortcut: "MCB", description: "Win/Door List", importance: 2 },
      { name: "yq_block_list", shortcut: "BBL", description: "Block List", importance: 1 },
      { name: "yq_attr_list", shortcut: "SXL", description: "Block Attribute List", importance: 1 },
      { name: "yq_collect_coords", shortcut: "ZZB", description: "Collect Coordinates", importance: 1 },
      { name: "yq_collect_strings", shortcut: "TTQ", description: "Collect Any Strings", importance: 1 },
      { name: "yq_material_list", shortcut: "CLB", description: "Material List", importance: 1 },
      { name: "yq_accum_area", shortcut: "MJ", description: "Accumulate Area", importance: 2 },
      { name: "yq_area_link", shortcut: "PMJ", description: "Area Link Text", importance: 1 },
      { name: "yq_accum_perimeter", shortcut: "ZC", description: "Accumulate Perimeter", importance: 1 },
      { name: "yq_perim_link", shortcut: "PZC", description: "Perimeter Link Text", importance: 1 },
      { name: "yq_calc_weight", shortcut: "ZL", description: "Calculate Weight", importance: 1 },
      { name: "yq_building_area", shortcut: "FTB", description: "Building Area Statistics", importance: 1 },
    ],
  },

  // ─── TEXT CONTENT ──────────────────────────────────────────────────
  {
    id: "text_content",
    label: "Text Content",
    description: "Text input, editing, find/replace, join, merge, break, increment, dictionary",
    commands: [
      { name: "yq_dictionary", shortcut: "DIC", description: "User Dictionary", importance: 1 },
      { name: "yq_translate", shortcut: "FY", description: "Translate Text", importance: 1 },
      { name: "yq_update_text", shortcut: "EQ", description: "Update Text From List", importance: 1 },
      { name: "yq_text", shortcut: "TT", description: "Input a Text", importance: 4 },
      { name: "yq_text_edit", shortcut: "TTE", description: "Modify Any Text", importance: 4 },
      { name: "yq_dict2text", shortcut: "TTG", description: "Dictionary to Text", importance: 1 },
      { name: "yq_create_texts", shortcut: "CTT", description: "Create/Input Texts", importance: 3 },
      { name: "yq_edit_texts", shortcut: "CED", description: "Edit/Output Texts", importance: 3 },
      { name: "yq_text_replace", shortcut: "TTR", description: "Replace/Calculate", importance: 4 },
      { name: "yq_text_replace_sub", shortcut: "TTRS", description: "Replace Substrings", importance: 2 },
      { name: "yq_text_join", shortcut: "TTA", description: "Join Texts", importance: 2 },
      { name: "yq_text_merge", shortcut: "TTJ", description: "Merge Multi-Line Text", importance: 2 },
      { name: "yq_text_break", shortcut: "TTB", description: "Break Text", importance: 2 },
      { name: "yq_text2chars", shortcut: "TTBB", description: "Text to Characters", importance: 1 },
      { name: "yq_increment_dup", shortcut: "1234", description: "Increment Duplicate", importance: 2 },
      { name: "yq_add_increment", shortcut: "INC", description: "Add Increment", importance: 2 },
      { name: "yq_increase_text", shortcut: "TTZ", description: "Increase Text", importance: 2 },
      { name: "yq_seek_text", shortcut: "TTF", description: "Seek Specific Text", importance: 2 },
      { name: "yq_exchange_content", shortcut: "JH", description: "Exchange Content", importance: 1 },
    ],
  },

  // ─── TEXT OTHER ────────────────────────────────────────────────────
  {
    id: "text_other",
    label: "Text Other",
    description: "Text styles, font replacement, alignment, mirroring, attribute conversion",
    commands: [
      { name: "yq_text_style", shortcut: "TTN", description: "New Text Style", importance: 2 },
      { name: "yq_set_text_style", shortcut: "TTS", description: "Set Current Style", importance: 2 },
      { name: "yq_update_by_style", shortcut: "TTU", description: "Update Text by Style", importance: 2 },
      { name: "yq_auto_replace_fonts", shortcut: "TTRF", description: "Auto Replace Fonts", importance: 1 },
      { name: "yq_changetext", shortcut: "TTC", description: "Change Text", importance: 4 },
      { name: "yq_change_height", shortcut: "TTW", description: "Change Height/Aspects", importance: 3 },
      { name: "yq_reorder_text", shortcut: "TTPX", description: "Reorder Table Text", importance: 1 },
      { name: "yq_text_align_left", shortcut: "TTL", description: "Text Alignment Left", importance: 2 },
      { name: "yq_text_align_right", shortcut: "TTLL", description: "Text Alignment Right", importance: 2 },
      { name: "yq_restore_mirrored", shortcut: "TTRR", description: "Restored Mirrored/Rot", importance: 1 },
      { name: "yq_convert_attdefs", shortcut: "TTSX", description: "Convert Texts/Attdefs", importance: 1 },
      { name: "yq_explode_texts", shortcut: "TTX", description: "Explode Texts to Line", importance: 1 },
    ],
  },

  // ─── DIMENSION DRAW ────────────────────────────────────────────────
  {
    id: "dimension_draw",
    label: "Dimension Draw",
    description: "Linear, aligned, baseline, radius, angular, quick, closed space, and special dimensioning",
    commands: [
      { name: "yq_dim_linear", shortcut: "DD", description: "Dim Linear", importance: 4 },
      { name: "yq_dim_aligned", shortcut: "DDX", description: "Dim Aligned", importance: 3 },
      { name: "yq_dim_baseline", shortcut: "DDB", description: "Dim Baseline", importance: 3 },
      { name: "yq_dim_radius", shortcut: "DDR", description: "Dim Radius", importance: 3 },
      { name: "yq_dim_diameter", shortcut: "DDJ", description: "Dim Diameter", importance: 3 },
      { name: "yq_dim_angular", shortcut: "DDAN", description: "Dim Angular", importance: 3 },
      { name: "yq_dim_arclen", shortcut: "DDAR", description: "Dim Arch Length", importance: 2 },
      { name: "yq_dim_3pt_arc", shortcut: "DDA3", description: "Dim 3 Point Arc", importance: 2 },
      { name: "yq_dim_qdim", shortcut: "DDQ", description: "Dim Quick", importance: 3 },
      { name: "yq_dim_closedspace", shortcut: "DDZ", description: "Dim Closed Space", importance: 4 },
      { name: "yq_dim_closedpline", shortcut: "DDZZ", description: "Dim Closed PLine", importance: 3 },
      { name: "yq_dim_plines", shortcut: "DDSS", description: "Dim PLine/Lines", importance: 3 },
      { name: "yq_dim_axiswd", shortcut: "DDW", description: "Dim of Axis/Windows", importance: 3 },
      { name: "yq_dim_blks_walls", shortcut: "DDWW", description: "Dim of Blocks/Walls", importance: 3 },
      { name: "yq_dim_cupboard", shortcut: "DDGZ", description: "Dim of Cupboard", importance: 2 },
      { name: "yq_dim_steps", shortcut: "DDST", description: "Dim of Steps", importance: 2 },
      { name: "yq_dim_fixlen", shortcut: "DDVD", description: "Dim Fix Length Parts", importance: 2 },
      { name: "yq_dim_breaks", shortcut: "DDXX", description: "Dim Breaks at Intersections", importance: 2 },
      { name: "yq_dim_chord", shortcut: "DDCC", description: "Dim Chord at Intersections", importance: 2 },
      { name: "yq_dim_arch", shortcut: "DDAC", description: "Dim Arch at Intersections", importance: 2 },
      { name: "yq_dim_rebuild", shortcut: "DDP", description: "Dim Rebuild by Texts", importance: 2 },
      { name: "yq_dim_merge", shortcut: "DDBB", description: "Dim Merge Baseline", importance: 2 },
      { name: "yq_dim_switch_layer", shortcut: "DDER", description: "Switch Dim Layer", importance: 2 },
      { name: "yq_dim_set_style", shortcut: "DDS", description: "Set Current DimStyle", importance: 3 },
      { name: "yq_dim_update", shortcut: "DDU", description: "Dim Update by Style", importance: 2 },
      { name: "yq_dim_switch_style", shortcut: "DDYQ", description: "Switch YQ DimStyle", importance: 2 },
    ],
  },

  // ─── DIMENSION MODIFY ──────────────────────────────────────────────
  {
    id: "dimension_modify",
    label: "Dimension Modify",
    description: "Adjust, extend, split, merge, align, lock, reset, and format dimension objects",
    commands: [
      { name: "yq_dim_adjust_text", shortcut: "DDAA", description: "Adjust Text Position", importance: 3 },
      { name: "yq_dim_extend", shortcut: "DDE", description: "Extend Dim Line", importance: 3 },
      { name: "yq_dim_split", shortcut: "DD2", description: "Split/Ext into Many", importance: 3 },
      { name: "yq_dim_merge_one", shortcut: "DD1", description: "Merge Dims", importance: 3 },
      { name: "yq_dim_align_pts", shortcut: "DDV", description: "Align Definition Points", importance: 2 },
      { name: "yq_dim_align_mline", shortcut: "DDVV", description: "Align Dim MLine", importance: 2 },
      { name: "yq_dim_align_feet", shortcut: "DDL", description: "Align Feet Point", importance: 2 },
      { name: "yq_dim_fix_ext", shortcut: "DDLE", description: "Fix Extension Lengths", importance: 2 },
      { name: "yq_dim_base_spacing", shortcut: "DDY", description: "Adjust Base Spacing", importance: 2 },
      { name: "yq_dim_batch_spacing", shortcut: "DDYY", description: "Batch Base Spacing", importance: 2 },
      { name: "yq_dim_show_ext", shortcut: "DD2E", description: "Show Extension Lines", importance: 1 },
      { name: "yq_dim_align_rotate", shortcut: "DDRA", description: "Aligned or Rotated", importance: 1 },
      { name: "yq_dim_overturn", shortcut: "DDFZ", description: "Overturn Dim Text", importance: 1 },
      { name: "yq_dim_lock", shortcut: "DDF", description: "Lock Text Content", importance: 2 },
      { name: "yq_dim_reset", shortcut: "DDRE", description: "Reset Default Value", importance: 2 },
      { name: "yq_dim_to_meter", shortcut: "DDM", description: "Units to Meter", importance: 1 },
      { name: "yq_dim_round", shortcut: "DDO", description: "Rounds Dim Value", importance: 1 },
      { name: "yq_dim_new_text", shortcut: "DDN", description: "New Dim Text", importance: 2 },
      { name: "yq_dim_move_text", shortcut: "DDT", description: "Move Dim Text", importance: 2 },
      { name: "yq_dim_reset_home", shortcut: "DDH", description: "Reset Dim Text Home", importance: 2 },
    ],
  },

  // ─── CURVE TOOLS ───────────────────────────────────────────────────
  {
    id: "curve_tools",
    label: "Curve Tools",
    description: "PLine vertex editing, join, close, reverse, border finding, freehand, ellipse/curve conversion",
    commands: [
      { name: "yq_add_vertex", shortcut: "XXV", description: "Add/Remove Vertexes", importance: 2 },
      { name: "yq_optimize_plines", shortcut: "XXY", description: "Optimize PLines", importance: 1 },
      { name: "yq_seg2arc", shortcut: "XXA", description: "PLine Segment to Arc", importance: 1 },
      { name: "yq_seg_width", shortcut: "XXW", description: "PLine Segment Width", importance: 1 },
      { name: "yq_seg_offset", shortcut: "XXS", description: "PLine Segment Offset", importance: 1 },
      { name: "yq_join_pline", shortcut: "XXJ", description: "Join PLine/Arc/Line", importance: 2 },
      { name: "yq_close_pline", shortcut: "XXC", description: "Close PLine/Arc/Line", importance: 2 },
      { name: "yq_reverse_curve", shortcut: "XXFZ", description: "Reserve Curve Direction", importance: 1 },
      { name: "yq_connect_vertices", shortcut: "LJX", description: "Connect 2 PLine Vertexes", importance: 1 },
      { name: "yq_find_border", shortcut: "LK", description: "Find Border/Outline", importance: 2 },
      { name: "yq_find_contours", shortcut: "NLK", description: "Find Inner Contours", importance: 2 },
      { name: "yq_contours_offset", shortcut: "NLKS", description: "Contours + Offset", importance: 1 },
      { name: "yq_freehand", shortcut: "HW", description: "Convert to Freehand", importance: 1 },
      { name: "yq_break_equal", shortcut: "DF", description: "Break to Equal Parts", importance: 1 },
      { name: "yq_divide_2pts", shortcut: "DFX", description: "Divide by 2 Points", importance: 1 },
      { name: "yq_ellipse2arcs", shortcut: "E2A", description: "Ellipse to Arcs", importance: 1 },
      { name: "yq_curve2arc", shortcut: "CCA", description: "Curve to Arc PLine", importance: 1 },
      { name: "yq_curve2line", shortcut: "CCX", description: "Curve to Line PLine", importance: 1 },
      { name: "yq_curve2bowstrings", shortcut: "CCXX", description: "Curve to Bowstrings", importance: 1 },
      { name: "yq_curve_projection", shortcut: "CCY", description: "Curve Projection", importance: 1 },
    ],
  },

  // ─── EXTRA TOOLS ───────────────────────────────────────────────────
  {
    id: "extra_tools",
    label: "Extra Tools",
    description: "Double lines, alignment, break, copy detail, transform, bounding box",
    commands: [
      { name: "yq_number_lines", shortcut: "VV", description: "Number Lines Manage", importance: 1 },
      { name: "yq_doubleline", shortcut: "XD", description: "Double Lines", importance: 3 },
      { name: "yq_trimdoubleline", shortcut: "TX", description: "Double Lines Scissor", importance: 3 },
      { name: "yq_doubleline_thk", shortcut: "XDT", description: "Double Line Thickness", importance: 2 },
      { name: "yq_to_doublelines", shortcut: "XXD", description: "To Double Lines", importance: 2 },
      { name: "yq_doubleline_offset", shortcut: "XDO", description: "Double Lines Offset", importance: 2 },
      { name: "yq_doubleline_axis", shortcut: "CE", description: "Axis of Double Lines", importance: 2 },
      { name: "yq_alignment", shortcut: "DQ", description: "Objects Alignment", importance: 3 },
      { name: "yq_leaders_alignment", shortcut: "AADQ", description: "Leaders Alignment", importance: 2 },
      { name: "yq_align_frame", shortcut: "TKTZ", description: "Align Frame with Line", importance: 1 },
      { name: "yq_break_knife", shortcut: "BD", description: "Break by a Knife", importance: 2 },
      { name: "yq_break_knives", shortcut: "BDD", description: "Break by Knives", importance: 2 },
      { name: "yq_break_frames", shortcut: "BX", description: "Break/Erase in Frames", importance: 2 },
      { name: "yq_copy_detail", shortcut: "QG", description: "Copy/Paste the Detail", importance: 2 },
      { name: "yq_transform", shortcut: "TF", description: "Transform", importance: 3 },
      { name: "yq_bounding_box", shortcut: "JX", description: "Bounding Box", importance: 2 },
      { name: "yq_to_bounding_box", shortcut: "WK", description: "To Bounding Box", importance: 1 },
      { name: "yq_min_bounding_box", shortcut: "XJX", description: "Minimum Bounding Box", importance: 1 },
      { name: "yq_turn_objects", shortcut: "FZX", description: "Turn Objects", importance: 2 },
      { name: "yq_exchange_location", shortcut: "JH", description: "Exchange Location", importance: 1 },
      { name: "yq_copy_to_points", shortcut: "DZBZ", description: "Copy to Points", importance: 2 },
    ],
  },

  // ─── MODIFY PLUS ───────────────────────────────────────────────────
  {
    id: "modify_plus",
    label: "Modify Plus",
    description: "Scale/rotate/mirror each, dynamic copy, stretch, move, super offset, extend, wipeout, break",
    commands: [
      { name: "yq_scale_each", shortcut: "ASC", description: "Scale for Each", importance: 2 },
      { name: "yq_rotate_each", shortcut: "ART", description: "Rotate for Each", importance: 2 },
      { name: "yq_mirror_each", shortcut: "AMI", description: "Mirror for Each", importance: 2 },
      { name: "yq_xy_scale", shortcut: "SCX", description: "XY Scale", importance: 2 },
      { name: "yq_dynamic_copy", shortcut: "CV", description: "Dynamic Copy", importance: 3 },
      { name: "yq_stretch_dist", shortcut: "STD", description: "Stretch with Distance", importance: 2 },
      { name: "yq_move_dist", shortcut: "VD", description: "Move with Distance", importance: 2 },
      { name: "yq_memorial_move", shortcut: "VR", description: "Memorial Move", importance: 2 },
      { name: "yq_memorial_copy", shortcut: "CR", description: "Memorial Copy", importance: 2 },
      { name: "yq_super_offset", shortcut: "SF", description: "Super Offset", importance: 3 },
      { name: "yq_extend_to", shortcut: "EXX", description: "Extend to Point/Line", importance: 2 },
      { name: "yq_link_arc", shortcut: "FF", description: "Link Arc/Line/PLine", importance: 2 },
      { name: "yq_connect_groups", shortcut: "FX", description: "Connect 2 Group Lines", importance: 1 },
      { name: "yq_wipeout", shortcut: "ZZ", description: "Add/Remove Wipeout", importance: 2 },
      { name: "yq_break_all", shortcut: "BA", description: "Break All Objects", importance: 2 },
      { name: "yq_break_erase", shortcut: "TE", description: "Break and Erase Remains", importance: 2 },
      { name: "yq_break_point", shortcut: "BB", description: "Break at a Point", importance: 2 },
      { name: "yq_break_2pts", shortcut: "BF", description: "Break at 2 Points", importance: 2 },
    ],
  },

  // ─── CHECK AND CORRECT ─────────────────────────────────────────────
  {
    id: "check_correct",
    label: "Check and Correct",
    description: "Z-axis clearing, overlap elimination, line merging, grid adjustment, purge, checks",
    commands: [
      { name: "yq_clear_z", shortcut: "ZO", description: "Clear Z-axis of Objects", importance: 2 },
      { name: "yq_clear_z_blocks", shortcut: "BBZO", description: "Clear Z-axis in Blocks", importance: 1 },
      { name: "yq_eliminate_overlap", shortcut: "RD", description: "Eliminate Overlapping", importance: 2 },
      { name: "yq_merge_lines", shortcut: "LU", description: "Merge Overlap Lines", importance: 2 },
      { name: "yq_connect_lines", shortcut: "LX", description: "Connect Lines/Arcs", importance: 2 },
      { name: "yq_remove_short", shortcut: "LC", description: "Remove Points/Short Lines", importance: 1 },
      { name: "yq_adjust_grid", shortcut: "JZ", description: "Adjust Objects to Grid", importance: 1 },
      { name: "yq_oblique_correction", shortcut: "XGZ", description: "Oblique Correction", importance: 1 },
      { name: "yq_dialog_merge", shortcut: "XHB", description: "Dialog Merge", importance: 1 },
      { name: "yq_purge_all", shortcut: "PUA", description: "Purge All in DWG", importance: 2 },
      { name: "yq_purge_folder", shortcut: "PUF", description: "Purge DWGs in Folder", importance: 1 },
      { name: "yq_check_color", shortcut: "CYS", description: "Check Object's Color", importance: 1 },
      { name: "yq_find_nonortho", shortcut: "BPX", description: "Find Non-Ortho Lines", importance: 1 },
      { name: "yq_find_unmatch", shortcut: "UM", description: "Find Unmatch WCS Plan", importance: 1 },
      { name: "yq_ortho_check", shortcut: "BCZ", description: "Orthoaxis Check", importance: 1 },
      { name: "yq_revcloud", shortcut: "YX", description: "Revcloud", importance: 2 },
      { name: "yq_comment_frame", shortcut: "STK", description: "Comment Frame", importance: 1 },
    ],
  },

  // ─── BLOCK & ATTRIBUTE ─────────────────────────────────────────────
  {
    id: "block_attribute",
    label: "Block & Attribute",
    description: "Block creation, editing, renaming, wipeout, exploding, attributes, block libraries",
    commands: [
      { name: "yq_heap_trees", shortcut: "ZW", description: "Heap Trees", importance: 1 },
      { name: "yq_landscape", shortcut: "HJ", description: "Landscape Analyzing", importance: 1 },
      { name: "yq_reset_layer_blocks", shortcut: "BB0", description: "Reset Layer in Blocks", importance: 2 },
      { name: "yq_change_basepoint", shortcut: "BBL", description: "Change Base Point", importance: 2 },
      { name: "yq_block_rename", shortcut: "BBR", description: "Block Rename", importance: 2 },
      { name: "yq_block_batch_rename", shortcut: "BBG", description: "Block Batch Rename", importance: 1 },
      { name: "yq_detail_block", shortcut: "BBD", description: "Create Detail Block", importance: 2 },
      { name: "yq_block_scale", shortcut: "BBS", description: "Set Block Scale", importance: 2 },
      { name: "yq_write_blocks", shortcut: "BBW", description: "Write Out Blocks", importance: 2 },
      { name: "yq_replace_dwg", shortcut: "BBTD", description: "Replace by DWG", importance: 2 },
      { name: "yq_create_block", shortcut: "BBN", description: "Create Block Quickly", importance: 2 },
      { name: "yq_append_block", shortcut: "BBA", description: "Append to a Block", importance: 2 },
      { name: "yq_erase_block_obj", shortcut: "BBE", description: "Erase Object of Block", importance: 2 },
      { name: "yq_copy_from_block", shortcut: "BBC", description: "Copy Objects from Block", importance: 2 },
      { name: "yq_block_wipeout", shortcut: "BBZZ", description: "Add/Del Block Wipeout", importance: 2 },
      { name: "yq_minsert_block", shortcut: "BBJM", description: "Create Minsert Block", importance: 1 },
      { name: "yq_explode_minsert", shortcut: "BBX", description: "Explode Minsert Blocks", importance: 1 },
      { name: "yq_explode_nested", shortcut: "BBXX", description: "Explode Nested Blocks", importance: 1 },
      { name: "yq_text2attr", shortcut: "BBSX", description: "Block Text to Attribute", importance: 1 },
      { name: "yq_modify_attr", shortcut: "SXG", description: "Modify Attributes", importance: 2 },
      { name: "yq_increase_attr", shortcut: "SXZ", description: "Increase Attributes", importance: 1 },
      { name: "yq_change_attr", shortcut: "SXC", description: "Change Attributes", importance: 2 },
      { name: "yq_attr2text", shortcut: "SXT", description: "Change Attribute to Text", importance: 1 },
      { name: "yq_erase_attr", shortcut: "SXE", description: "Erase Attribute in Block", importance: 1 },
      { name: "yq_block_library", shortcut: "KK", description: "YQ Block Library", importance: 2 },
      { name: "yq_user_library", shortcut: "BV", description: "User Block Library", importance: 2 },
      { name: "yq_user_library1", shortcut: "BV1", description: "User Block Library 1", importance: 2 },
      { name: "yq_user_library2", shortcut: "BV2", description: "User Block Library 2", importance: 2 },
      { name: "yq_user_library3", shortcut: "BV3", description: "User Block Library 3", importance: 2 },
    ],
  },

  // ─── HATCHING & LINETYPE ───────────────────────────────────────────
  {
    id: "hatching_linetype",
    label: "Hatching & Linetype",
    description: "Hatching shortcuts, quick hatch, templates, clipping, split, union, linetype tools",
    commands: [
      { name: "yq_hatch_shortcuts", shortcut: "HHSC", description: "Hatching Shortcuts", importance: 3 },
      { name: "yq_hatch_scale", shortcut: "XTC", description: "Change Hatching Scale", importance: 3 },
      { name: "yq_quick_hatch", shortcut: "TC", description: "Quick Hatching", importance: 3 },
      { name: "yq_hatch_template", shortcut: "TCT", description: "Hatching by Template", importance: 2 },
      { name: "yq_param_hatch", shortcut: "TCC", description: "Param/Slide Hatch", importance: 2 },
      { name: "yq_hatch_basepoint", shortcut: "HHL", description: "Set Hatch Base Point", importance: 2 },
      { name: "yq_hatch_angle", shortcut: "HHA", description: "Hatching Angle", importance: 2 },
      { name: "yq_hatch_border", shortcut: "HHB", description: "Hatching Border", importance: 2 },
      { name: "yq_hatch_clip", shortcut: "HHJ", description: "Hatching Clipping", importance: 2 },
      { name: "yq_hatch_split", shortcut: "HHX", description: "Split Hatching", importance: 2 },
      { name: "yq_hatch_union", shortcut: "HHU", description: "Hatching Union", importance: 2 },
      { name: "yq_hatch_dissociate", shortcut: "HHGL", description: "Hatching Disassociate", importance: 1 },
      { name: "yq_make_pat_1mm", shortcut: "MP", description: "Make Hatch Pat 1mm", importance: 1 },
      { name: "yq_make_pat_1to1", shortcut: "MP1", description: "Make Hatch Pat 1:1", importance: 1 },
      { name: "yq_make_pat_hatch", shortcut: "MPP", description: "Make Pat by Hatch", importance: 1 },
      { name: "yq_linetype_shortcuts", shortcut: "LTSC", description: "Linetype Shortcuts", importance: 2 },
      { name: "yq_linetype_scale", shortcut: "XTC", description: "Change Linetype Scale", importance: 2 },
      { name: "yq_linetype_switch", shortcut: "XTS", description: "Linetype Switch", importance: 2 },
      { name: "yq_replace_lt_scale", shortcut: "PLTS", description: "Replace LT Scale", importance: 1 },
      { name: "yq_make_linetype", shortcut: "MLT", description: "Make Letter Linetype", importance: 1 },
      { name: "yq_load_linetypes", shortcut: "ILT", description: "Load Linetypes", importance: 1 },
    ],
  },

  // ─── LAYER TOOLS ───────────────────────────────────────────────────
  {
    id: "layer_tools",
    label: "Layer Tools",
    description: "Layer creation, isolation, on/off, lock/unlock, freeze/thaw, batch operations, shortcuts",
    commands: [
      { name: "yq_layer_to_current", shortcut: "ENC", description: "Change to Current Layer", importance: 3 },
      { name: "yq_layer_new", shortcut: "ERN", description: "Make a New Layer", importance: 3 },
      { name: "yq_layer_current", shortcut: "ERS", description: "Set Current Layer", importance: 3 },
      { name: "yq_layer_save_restore", shortcut: "ERR", description: "Save/Restore Layers", importance: 2 },
      { name: "yq_layer_wildcard", shortcut: "ERQ", description: "Wildcard Layers", importance: 2 },
      { name: "yq_layer_isolate", shortcut: "ERD", description: "Isolate Layers", importance: 3 },
      { name: "yq_layer_off", shortcut: "ERF", description: "Turn Off Layers", importance: 3 },
      { name: "yq_layer_off_all", shortcut: "ERAF", description: "Turn Off All Layers", importance: 2 },
      { name: "yq_layer_on", shortcut: "ERA", description: "Turn On Layers", importance: 3 },
      { name: "yq_layer_on_all", shortcut: "ERAA", description: "Turn On All Layers", importance: 2 },
      { name: "yq_layer_toggle", shortcut: "ERV", description: "All Layers On/Off", importance: 2 },
      { name: "yq_layer_lock", shortcut: "ERL", description: "Lock Layers", importance: 2 },
      { name: "yq_layer_isolate_lock", shortcut: "ERDL", description: "Isolate Lock", importance: 2 },
      { name: "yq_layer_unlock", shortcut: "ERU", description: "Unlock Layers", importance: 2 },
      { name: "yq_layer_freeze", shortcut: "ERZ", description: "Freeze Layers", importance: 2 },
      { name: "yq_layer_isolate_freeze", shortcut: "ERDZ", description: "Isolate Freeze", importance: 2 },
      { name: "yq_layer_thaw", shortcut: "ERT", description: "Thaw Out Layers", importance: 2 },
      { name: "yq_layer_off_block", shortcut: "ERBF", description: "Turn Off in Block", importance: 1 },
      { name: "yq_layer_freeze_block", shortcut: "ERBZ", description: "Freeze in Block", importance: 1 },
      { name: "yq_layer_thaw_all", shortcut: "ERER", description: "Thaw/Unlock/Open All", importance: 2 },
      { name: "yq_layer_batch_replace", shortcut: "ERTD", description: "Batch Replace Layers", importance: 2 },
      { name: "yq_layer_batch_rename", shortcut: "ERG", description: "Layers Batch Rename", importance: 1 },
      { name: "yq_layer_merge", shortcut: "ERM", description: "Merge Layers", importance: 2 },
      { name: "yq_layer_from_color", shortcut: "C2ER", description: "Form Layers by Color", importance: 1 },
      { name: "yq_layer_shortcuts", shortcut: "ERSC", description: "Layer Shortcuts", importance: 2 },
      { name: "yq_layer_wildcard_sc", shortcut: "ERW", description: "Wildcard Layer Shortcuts", importance: 2 },
      { name: "yq_color_shortcuts", shortcut: "ERK", description: "Color Shortcuts", importance: 2 },
      { name: "yq_layer_export", shortcut: "ERO", description: "Output Layer Text File", importance: 1 },
      { name: "yq_layer_import", shortcut: "ERI", description: "Input Layer Text File", importance: 1 },
    ],
  },

  // ─── VIEWPORT LAYOUT TOOLS ─────────────────────────────────────────
  {
    id: "viewport_layout",
    label: "Viewport Layout Tools",
    description: "Viewport layer management, creation, scaling, locking, paper space, layouts",
    commands: [
      { name: "yq_vport_manager", shortcut: "VVC", description: "VPort Layer Manager", importance: 2 },
      { name: "yq_vport_freeze", shortcut: "VVZ", description: "Freeze Viewport Layers", importance: 2 },
      { name: "yq_vport_freeze_block", shortcut: "VVBZ", description: "Freeze Block VP Layer", importance: 1 },
      { name: "yq_vport_thaw", shortcut: "VVT", description: "Thaw VPort Layers", importance: 2 },
      { name: "yq_vport_isolate", shortcut: "VVDZ", description: "Isolate VP Layers", importance: 2 },
      { name: "yq_vport_isolate_other", shortcut: "VVZZ", description: "Isolate Other VP Layers", importance: 1 },
      { name: "yq_vport_gray", shortcut: "VVH", description: "Grayed VP Layers", importance: 1 },
      { name: "yq_vport_recover_color", shortcut: "VVHF", description: "Recover VP Layer Color", importance: 1 },
      { name: "yq_vport_new", shortcut: "VVN", description: "New Viewport", importance: 2 },
      { name: "yq_vport_split", shortcut: "VV2", description: "Viewport Split", importance: 2 },
      { name: "yq_vport_from_model", shortcut: "MVV", description: "Viewport from Model Space", importance: 2 },
      { name: "yq_curve2vport", shortcut: "XXVV", description: "Curve to Viewport", importance: 1 },
      { name: "yq_vport_scale", shortcut: "VVS", description: "Set Viewport Scale", importance: 2 },
      { name: "yq_vport_scale_batch", shortcut: "VVSC", description: "Scale Viewports", importance: 2 },
      { name: "yq_vport_sync", shortcut: "VVDQ", description: "VP Content Sync", importance: 2 },
      { name: "yq_vport_pan", shortcut: "VVP", description: "Viewport Pan", importance: 2 },
      { name: "yq_vport_lock", shortcut: "VVL", description: "Lock Viewports", importance: 2 },
      { name: "yq_vport_lock_all", shortcut: "VVAL", description: "Lock All Viewports", importance: 2 },
      { name: "yq_vport_unlock", shortcut: "VVU", description: "Unlock Viewports", importance: 2 },
      { name: "yq_vport_unlock_all", shortcut: "VVAU", description: "Unlock All Viewports", importance: 1 },
      { name: "yq_vport_isolate_vp", shortcut: "VVD", description: "Isolate Viewports", importance: 2 },
      { name: "yq_vport_off", shortcut: "VVF", description: "Turn Off Viewports", importance: 2 },
      { name: "yq_vport_off_all", shortcut: "VVAF", description: "Turn Off All Viewports", importance: 1 },
      { name: "yq_vport_on", shortcut: "VVA", description: "Turn On Viewports", importance: 2 },
      { name: "yq_vport_on_all", shortcut: "VVAA", description: "Turn On All Viewports", importance: 1 },
      { name: "yq_copy_paper", shortcut: "VVBB", description: "Copy to Paper Space", importance: 2 },
      { name: "yq_rename_layouts", shortcut: "TZG", description: "Rename Layouts", importance: 1 },
      { name: "yq_frame2layouts", shortcut: "TZF", description: "Frame to Layouts", importance: 2 },
      { name: "yq_frame_divides", shortcut: "TZFG", description: "Frame Range Divides", importance: 1 },
      { name: "yq_vport_rotate", shortcut: "VVR", description: "Rotate Viewport Direction", importance: 2 },
      { name: "yq_snapshot", shortcut: "KZ", description: "Snapshot of a View", importance: 1 },
      { name: "yq_hyperlink_views", shortcut: "CLJ", description: "Hyperlink Views", importance: 1 },
    ],
  },

  // ─── MATCHING BRUSH ────────────────────────────────────────────────
  {
    id: "matching_brush",
    label: "Matching Brush",
    description: "Match and replace block, layer, color, text, linetype, and other properties",
    commands: [
      { name: "yq_match_block", shortcut: "SSB", description: "Match/Replace Block", importance: 2 },
      { name: "yq_match_dynamic", shortcut: "SSD", description: "Match Dynamic Props", importance: 2 },
      { name: "yq_match_rotation", shortcut: "SSA", description: "Match Rotation Angle", importance: 2 },
      { name: "yq_match_layer", shortcut: "SSER", description: "Match Layer", importance: 2 },
      { name: "yq_match_color", shortcut: "SSC", description: "Match Color", importance: 2 },
      { name: "yq_match_layer_color", shortcut: "SSCC", description: "Match Layer and Color", importance: 2 },
      { name: "yq_match_vport_layer", shortcut: "SSVV", description: "Match Viewport Layers", importance: 1 },
      { name: "yq_match_text", shortcut: "SST", description: "Match Text Content", importance: 2 },
      { name: "yq_match_text_style", shortcut: "SSST", description: "Match Text Style", importance: 2 },
      { name: "yq_match_text_height", shortcut: "SSH", description: "Match Text Height", importance: 2 },
      { name: "yq_match_by_attr", shortcut: "SSQ", description: "Match Text by Attribute Tag", importance: 1 },
      { name: "yq_match_pline_width", shortcut: "SSW", description: "Match Width of PLine", importance: 1 },
      { name: "yq_match_linetype", shortcut: "SSXT", description: "Match LineType", importance: 2 },
      { name: "yq_match_thickness", shortcut: "SSTH", description: "Match Thickness", importance: 1 },
    ],
  },

  // ─── OTHER TOOLS ───────────────────────────────────────────────────
  {
    id: "other_tools",
    label: "Other Tools",
    description: "Batch plot, DWG catalog, hide/display objects, groups, dynamic input, command finder",
    commands: [
      { name: "yq_batch_plot", shortcut: "BPT", description: "Batch Plot", importance: 2 },
      { name: "yq_dwg_catalog", shortcut: "DWGL", description: "Drawing Catalog", importance: 1 },
      { name: "yq_output_dwgs", shortcut: "DWGS", description: "Output DWGs Batches", importance: 1 },
      { name: "yq_arrange_frames", shortcut: "DWGA", description: "Arrange Frames/DWGs", importance: 1 },
      { name: "yq_reset_layer", shortcut: "EEO", description: "Reset Objects Layer", importance: 2 },
      { name: "yq_hide_objects", shortcut: "EEF", description: "Hide Objects", importance: 2 },
      { name: "yq_hide_unselected", shortcut: "EED", description: "Hide Unselected", importance: 2 },
      { name: "yq_display_hidden", shortcut: "EEA", description: "Display Temp Hidden", importance: 2 },
      { name: "yq_display_all", shortcut: "EEAA", description: "Display All Objects", importance: 2 },
      { name: "yq_create_group", shortcut: "GGN", description: "Create a Group", importance: 2 },
      { name: "yq_explode_group", shortcut: "GGX", description: "Explode a Group", importance: 2 },
      { name: "yq_append_group", shortcut: "GGA", description: "Append to a Group", importance: 1 },
      { name: "yq_erase_group", shortcut: "GGE", description: "Erase from a Group", importance: 1 },
      { name: "yq_separate_group", shortcut: "GGS", description: "Separate from Group", importance: 1 },
      { name: "yq_purge_groups", shortcut: "GGP", description: "Purge Groups", importance: 1 },
      { name: "yq_switch_dynamic", shortcut: "DTYQ", description: "Switch YQArch Dynamic", importance: 1 },
      { name: "yq_excel_points", shortcut: "ZTB", description: "Excel Clipboard Points", importance: 1 },
      { name: "yq_to_google_earth", shortcut: "A2K", description: "To Google Earth", importance: 1 },
      { name: "yq_command_finder", shortcut: "ZML", description: "YQArch Command Finder", importance: 1 },
      { name: "yq_last_command", shortcut: "QQ", description: "Last YQArch Command", importance: 2 },
    ],
  },
];

// Build lookup indexes
export const allCommandNames = new Set<string>();
export const commandIndex = new Map<string, CommandDef>();

for (const cat of categories) {
  for (const cmd of cat.commands) {
    allCommandNames.add(cmd.name);
    commandIndex.set(cmd.name, cmd);
  }
}
