/**
 * Complete registry of all 684 architectural commands, categorized.
 * Used by yq_list_commands for discovery and yq_execute for validation.
 */

export interface YqCommand {
  name: string;
  description: string;
}

export interface YqCategory {
  id: string;
  label: string;
  description: string;
  commands: YqCommand[];
}

export const categories: YqCategory[] = [
  // ─── 1. WALLS ───
  {
    id: "walls",
    label: "Murs / Walls",
    description: "Traçage, modification et découpe de murs",
    commands: [
      { name: "YQ_WALL", description: "Tracer un mur double ligne" },
      { name: "YQ_SIMPLE_WALL", description: "Mur simple (une ligne)" },
      { name: "YQ_LINE2WALL", description: "Convertir une ligne en mur" },
      { name: "YQ_FILL_WALL", description: "Remplir/hachurer un mur" },
      { name: "YQ_ERASE_WALL", description: "Effacer un mur" },
      { name: "YQ_AREAWALL", description: "Mur par zone/surface fermée" },
      { name: "YQ_WALL_CHGTHK", description: "Changer l'épaisseur d'un mur" },
      { name: "YQ_WALL_CDOFFSET", description: "Décaler l'axe du mur" },
      { name: "YQ_WALL2AXIS", description: "Extraire l'axe d'un mur" },
      { name: "YQ_PARTITIONWALL", description: "Mur de cloison" },
      { name: "YQ_DOUBLELINE", description: "Double ligne (longrine/fondation)" },
      { name: "YQ_DOUBLELINEAXIS", description: "Axe de double ligne" },
      { name: "YQ_DLINETHICKNESS", description: "Épaisseur de double ligne" },
      { name: "YQ_DLINE_OFFSET", description: "Décalage de double ligne" },
      { name: "YQ_2DOUBLELINE", description: "Convertir en double ligne" },
      { name: "YQ_CURTAINWALL", description: "Mur-rideau" },
      { name: "YQ_TRIMCURTAINWALL", description: "Ajuster mur-rideau" },
      { name: "YQ_TRIM_EWALL", description: "Ajuster extrémité de mur" },
      { name: "YQ_TRIM_FIX_WALL", description: "Réparer intersection de murs" },
      { name: "YQ_TRIM_TWALL", description: "Ajuster mur en T" },
      { name: "YQ_TRIM_XWALL", description: "Ajuster mur en croix" },
      { name: "YQ_TRIMDOUBLELINE", description: "Ajuster double ligne" },
    ],
  },

  // ─── 2. DOORS & WINDOWS ───
  {
    id: "doors_windows",
    label: "Portes & Fenêtres / Doors & Windows",
    description: "Insertion, modification et gestion de portes et fenêtres",
    commands: [
      { name: "YQ_DOOR", description: "Insérer une porte" },
      { name: "YQ_WINDOW", description: "Insérer une fenêtre" },
      { name: "YQ_WINDOWDOOR", description: "Porte-fenêtre" },
      { name: "YQ_POCKETDOOR", description: "Porte à galandage" },
      { name: "YQ_HOLE_DOOR", description: "Percement de porte dans mur" },
      { name: "YQ_HOLE_WIN", description: "Percement de fenêtre dans mur" },
      { name: "YQ_HOLE_WINDOW", description: "Percement fenêtre (variante)" },
      { name: "YQ_HOLE_CORNERWINDOW", description: "Fenêtre d'angle" },
      { name: "YQ_HOLE_POCKETDOOR", description: "Percement porte à galandage" },
      { name: "YQ_HOLE", description: "Percement générique dans mur" },
      { name: "YQ_MOVE_WINDOOR", description: "Déplacer porte/fenêtre" },
      { name: "YQ_WINDOOR_LIST", description: "Liste des menuiseries" },
      { name: "YQ_WINDOOR_REPLACE", description: "Remplacer menuiserie" },
      { name: "YQ_WINDOW_REPLACE", description: "Remplacer fenêtre" },
      { name: "YQ_CWINDOW_REPLACE", description: "Remplacer fenêtre d'angle" },
      { name: "YQ_POCKETDOOR_REPLACE", description: "Remplacer porte à galandage" },
      { name: "YQ_WIDTH_WINDOOR", description: "Modifier largeur menuiserie" },
      { name: "YQ_MATCH_WINDOOR", description: "Copier propriétés menuiserie" },
      { name: "YQ_DOOR_ELEVATION", description: "Élévation de porte" },
      { name: "YQ_DOOR_SECTION", description: "Coupe de porte" },
      { name: "YQ_DOOROPENING", description: "Ouverture de porte" },
      { name: "YQ_DOORSILL", description: "Seuil de porte" },
      { name: "YQ_WINDOW_ELEVATION", description: "Élévation de fenêtre" },
      { name: "YQ_WINDOW_SECTION", description: "Coupe de fenêtre" },
      { name: "YQ_BAYWIN_SECTION", description: "Coupe fenêtre en baie" },
      { name: "YQ_LINE2WINDOW", description: "Convertir ligne en fenêtre" },
      { name: "YQ_LINES2WINELEV", description: "Lignes vers élévation fenêtre" },
      { name: "YQ_SN2WINELEV", description: "Numéro série vers élévation fenêtre" },
      { name: "YQ_WINSERIALNUMBER", description: "Numérotation des fenêtres" },
      { name: "YQ_SHUTTER", description: "Volet/persienne" },
      { name: "YQ_CURTAINGLASS", description: "Vitrage mur-rideau" },
      { name: "YQ_CURTAINPLAN", description: "Plan mur-rideau" },
      { name: "YQ_GLASS", description: "Vitrage" },
      { name: "YQ_GLASS_PARTITION", description: "Cloison vitrée" },
    ],
  },

  // ─── 3. COLUMNS ───
  {
    id: "columns",
    label: "Poteaux / Columns",
    description: "Création et modification de poteaux structurels",
    commands: [
      { name: "YQ_R_COLUMN", description: "Poteau rectangulaire" },
      { name: "YQ_C_COLUMN", description: "Poteau circulaire" },
      { name: "YQ_L_COLUMN", description: "Poteau en L" },
      { name: "YQ_T_COLUMN", description: "Poteau en T" },
      { name: "YQ_O_COLUMN", description: "Poteau creux/annulaire" },
      { name: "YQ_FILL_COLUMN", description: "Remplir un poteau" },
      { name: "YQ_AXIS_COLUMN", description: "Poteau sur axe" },
      { name: "YQ_WALLCOLUMN", description: "Poteau dans mur" },
      { name: "YQ_PLINE2COLUMN", description: "Convertir polyligne en poteau" },
    ],
  },

  // ─── 4. STAIRS ───
  {
    id: "stairs",
    label: "Escaliers / Stairs",
    description: "Création d'escaliers en plan et en coupe",
    commands: [
      { name: "YQ_STAIRCASE_PLAN", description: "Plan d'escalier droit" },
      { name: "YQ_STAIRCASE_SECTION", description: "Coupe d'escalier" },
      { name: "YQ_ARCSTAIR_PLAN", description: "Plan d'escalier courbe" },
      { name: "YQ_STEP_SECTION", description: "Section de marche" },
      { name: "YQ_DIM_STAIRS", description: "Cotation d'escalier" },
      { name: "YQ_ESCALATOR", description: "Escalier mécanique/escalator" },
      { name: "YQ_BANISTER", description: "Garde-corps/rampe" },
      { name: "YQ_LIFT_PLAN", description: "Plan d'ascenseur" },
    ],
  },

  // ─── 5. DIMENSIONS ───
  {
    id: "dimensions",
    label: "Cotation / Dimensions",
    description: "Cotation automatique, manuelle et outils de cote",
    commands: [
      { name: "YQ_DIM_AUTO", description: "Cotation automatique des murs" },
      { name: "YQ_DIM_ALIGNED", description: "Cotation alignée" },
      { name: "YQ_DIM_LINEAR", description: "Cotation linéaire" },
      { name: "YQ_DIM_ARC", description: "Cotation d'arc" },
      { name: "YQ_DIM_ARC3PTS", description: "Cotation arc 3 points" },
      { name: "YQ_DIM_ARCPARTS", description: "Cotation parties d'arc" },
      { name: "YQ_DIM_ARCS", description: "Cotation de plusieurs arcs" },
      { name: "YQ_DIM_ANGULAR", description: "Cotation angulaire" },
      { name: "YQ_DIM_RADIUS", description: "Cotation de rayon" },
      { name: "YQ_DIM_DIAMETER", description: "Cotation de diamètre" },
      { name: "YQ_DIM_BASELINE", description: "Cotation depuis ligne de base" },
      { name: "YQ_DIM_BATCHBASE", description: "Cotation base par lot" },
      { name: "YQ_DIM_CONTINUE", description: "Cotation continue" },
      { name: "YQ_DIM_PLINE", description: "Cotation de polyligne" },
      { name: "YQ_DIM_QDIM", description: "Cotation rapide" },
      { name: "YQ_DIM_SLOPE", description: "Cotation de pente" },
      { name: "YQ_DIM_BLOCKS", description: "Cotation de blocs" },
      { name: "YQ_DIM_CLOSEDSPACE", description: "Cotation espace fermé" },
      { name: "YQ_DIM_CUPBOARD", description: "Cotation de placard" },
      { name: "YQ_DIM_CURVEINTPTS", description: "Cotation points d'intersection courbe" },
      { name: "YQ_DIM_INTPTS", description: "Cotation points d'intersection" },
      { name: "YQ_DIM_DIVIDE", description: "Diviser une cote" },
      { name: "YQ_DIM_DVD", description: "Division de cote (variante)" },
      { name: "YQ_DIM_POLYGONANGLES", description: "Cotation angles de polygone" },
      { name: "YQ_DIM_POLYGONSIDES", description: "Cotation côtés de polygone" },
      { name: "YQ_DIM_AXISWD", description: "Cotation largeur d'axe" },
      { name: "YQ_AUTO_AXIS_DIM", description: "Cotation automatique des axes" },
      { name: "YQ_DIM_ADJUST", description: "Ajuster cote" },
      { name: "YQ_DIM_ADJUSTBASE", description: "Ajuster ligne de base de cote" },
      { name: "YQ_DIM_ALIGN", description: "Aligner les cotes" },
      { name: "YQ_DIM_ALIGNDIMLINE", description: "Aligner lignes de cote" },
      { name: "YQ_DIM_ALIGNPOINTS", description: "Aligner points de cote" },
      { name: "YQ_DIM_DEL0", description: "Supprimer cotes à zéro" },
      { name: "YQ_DIM_EXTEND", description: "Étendre une cote" },
      { name: "YQ_DIM_EXTLEN", description: "Longueur d'extension de cote" },
      { name: "YQ_DIM_FIX", description: "Fixer/corriger une cote" },
      { name: "YQ_DIM_HOME", description: "Ramener cote à position d'origine" },
      { name: "YQ_DIM_MERGE", description: "Fusionner des cotes" },
      { name: "YQ_DIM_MERGEBASE", description: "Fusionner cotes de base" },
      { name: "YQ_DIM_MMTOM", description: "Convertir cotes mm vers m" },
      { name: "YQ_DIM_NEWTEXT", description: "Nouveau texte de cote" },
      { name: "YQ_DIM_REARRANGE", description: "Réorganiser les cotes" },
      { name: "YQ_DIM_RECOVER", description: "Récupérer cote endommagée" },
      { name: "YQ_DIM_REVERSE", description: "Inverser le sens d'une cote" },
      { name: "YQ_DIM_ROUND", description: "Arrondir valeurs de cotes" },
      { name: "YQ_DIM_SHOWEXTLINE", description: "Afficher lignes d'extension" },
      { name: "YQ_DIM_SWITCH_AR", description: "Basculer flèches de cote" },
      { name: "YQ_DIM_SWITCHLAYER", description: "Changer calque des cotes" },
      { name: "YQ_DIM_SWITCHSTYLE", description: "Changer style de cote" },
      { name: "YQ_DIM_CSTYLE", description: "Style de cote courant" },
      { name: "YQ_DIM_TEDIT", description: "Éditer texte de cote" },
      { name: "YQ_DIM_UPDATE", description: "Mettre à jour les cotes" },
      { name: "YQ_DIM2LINES", description: "Cotes vers lignes" },
      { name: "YQ_DIMDRAW", description: "Dessiner une cote" },
      { name: "YQ_DIMMODIFY", description: "Modifier une cote" },
      { name: "YQ_DIMSTRETCH", description: "Étirer une cote" },
      { name: "YQ_NEWDIMSTYLE", description: "Créer nouveau style de cote" },
      { name: "YQ_FIXPSDIMSCALE", description: "Corriger échelle cote en PS" },
    ],
  },

  // ─── 6. GRID & AXES ───
  {
    id: "grid_axes",
    label: "Axes & Grilles / Grid & Axes",
    description: "Grilles structurelles et lignes d'axe",
    commands: [
      { name: "YQ_GRIDAXIS", description: "Grille d'axes structurelle" },
      { name: "YQ_AXISLINE", description: "Ligne d'axe" },
      { name: "YQ_SYMMETRY_AXIS", description: "Axe de symétrie" },
      { name: "YQ_CENTRAL_LINE", description: "Ligne centrale" },
      { name: "YQ_CHECKORTHOAXIS", description: "Vérifier orthogonalité des axes" },
      { name: "YQ_SYMBOL_AXIS_C", description: "Symbole d'axe circulaire" },
      { name: "YQ_ASSISTANTLINES", description: "Lignes d'aide/construction" },
      { name: "YQ_CROSSXLINE", description: "Lignes croisées" },
      { name: "YQ_ANGLEXLINE", description: "Ligne de construction angulaire" },
    ],
  },

  // ─── 7. HATCHING & MATERIALS ───
  {
    id: "hatching",
    label: "Hachures & Matériaux / Hatching & Materials",
    description: "Hachures, revêtements et matériaux de construction",
    commands: [
      { name: "YQ_HATCH_QUICK", description: "Hachure rapide" },
      { name: "YQ_HATCH_MATCH", description: "Copier propriétés de hachure" },
      { name: "YQ_HATCH_ANGLE", description: "Modifier angle de hachure" },
      { name: "YQ_HATCH_BORDER", description: "Bordure de hachure" },
      { name: "YQ_HATCH_CLIPPING", description: "Découper hachure" },
      { name: "YQ_HATCH_DISASSO", description: "Dissocier hachure" },
      { name: "YQ_HATCH_NEWBASE", description: "Nouveau point de base hachure" },
      { name: "YQ_HATCH_SLIDE", description: "Glisser hachure" },
      { name: "YQ_HATCH_SPLIT", description: "Diviser hachure" },
      { name: "YQ_HATCH_UNION", description: "Unir hachures" },
      { name: "YQ_HATCHAREA", description: "Aire d'une hachure" },
      { name: "YQ_HATCHINGSCALE", description: "Échelle de hachure" },
      { name: "YQ_HATCHINGTOOLS", description: "Outils de hachures" },
      { name: "YQ_HATCHKEYS", description: "Raccourcis hachures" },
      { name: "YQ_INSULATION", description: "Hachure isolation thermique" },
      { name: "YQ_STONETILE", description: "Carrelage/pierre" },
      { name: "YQ_WOODFLOORING", description: "Parquet/bois" },
      { name: "YQ_WATERPROOF", description: "Étanchéité" },
      { name: "YQ_GYPSUMBOARD", description: "Plaque de plâtre" },
      { name: "YQ_PLYWOOD", description: "Contreplaqué" },
      { name: "YQ_STUCCO", description: "Enduit/crépi" },
      { name: "YQ_PLASTERSTRINGPLAN", description: "Plan de moulure en plâtre" },
      { name: "YQ_S2H", description: "Convertir SOLID en HATCH" },
      { name: "YQ_MKPAT", description: "Créer motif de hachure personnalisé" },
      { name: "YQ_MKPAT_BYHATCH", description: "Motif depuis hachure existante" },
      { name: "YQ_MKPAT1", description: "Créer motif simple" },
    ],
  },

  // ─── 8. LAYERS ───
  {
    id: "layers",
    label: "Calques / Layers",
    description: "Gestion complète des calques AutoCAD",
    commands: [
      { name: "YQ_LAYER_NEW", description: "Créer nouveau calque" },
      { name: "YQ_LAYER_CURRENT", description: "Définir calque courant" },
      { name: "YQ_LAYER_2CURRENT", description: "Déplacer objets vers calque courant" },
      { name: "YQ_LAYER_OFF", description: "Éteindre calque" },
      { name: "YQ_LAYER_OFF_ALL", description: "Éteindre tous les calques" },
      { name: "YQ_LAYER_ON", description: "Allumer calque" },
      { name: "YQ_LAYER_ON_ALL", description: "Allumer tous les calques" },
      { name: "YQ_LAYER_ON2OFF", description: "Inverser calques on/off" },
      { name: "YQ_LAYER_NOFF", description: "Éteindre calque (non-courant)" },
      { name: "YQ_LAYER_FREEZE", description: "Geler calque" },
      { name: "YQ_LAYER_THAW", description: "Dégeler calque" },
      { name: "YQ_LAYER_NFREEZE", description: "Geler calque (non-courant)" },
      { name: "YQ_LAYER_LOCK", description: "Verrouiller calque" },
      { name: "YQ_LAYER_UNLOCK", description: "Déverrouiller calque" },
      { name: "YQ_LAYER_ISO", description: "Isoler calque" },
      { name: "YQ_LAYER_ISO_FREEZE", description: "Isoler calque (geler les autres)" },
      { name: "YQ_LAYER_ISO_LOCK", description: "Isoler calque (verrouiller les autres)" },
      { name: "YQ_LAYER_SHOWALL", description: "Afficher tous les calques" },
      { name: "YQ_LAYER_RENAME", description: "Renommer calque" },
      { name: "YQ_LAYER_BATCHRENAME", description: "Renommer calques par lot" },
      { name: "YQ_LAYER_REPLACE", description: "Remplacer calque" },
      { name: "YQ_LAYER_SAVERESTORE", description: "Sauver/restaurer états de calques" },
      { name: "YQ_LAYERTOOLS", description: "Outils de calques" },
      { name: "YQ_LAYERFILTER", description: "Filtre de calques" },
      { name: "YQ_LAYERKEYS", description: "Raccourcis calques" },
      { name: "YQ_CALLAYER", description: "Appeler calque (sélection par objet)" },
      { name: "YQ_INPUTLAYERS", description: "Importer calques" },
      { name: "YQ_ERASELAYER", description: "Effacer tout le contenu d'un calque" },
      { name: "YQ_COPYTOLAYER", description: "Copier objet vers un calque" },
      { name: "YQ_MERGE_LAYER", description: "Fusionner calques" },
      { name: "YQ_ALL2LAYER", description: "Tout déplacer vers un calque" },
      { name: "YQ_WLAYER", description: "Calques de menuiseries" },
      { name: "YQ_WLAYERKEYS", description: "Raccourcis calques menuiseries" },
      { name: "YQ_FORMLAYBYCOLOR", description: "Créer calques par couleur" },
      { name: "YQ_LAYOUT_BATCHRENAME", description: "Renommer présentations par lot" },
    ],
  },

  // ─── 9. BLOCKS ───
  {
    id: "blocks",
    label: "Blocs / Blocks",
    description: "Gestion des blocs AutoCAD",
    commands: [
      { name: "YQ_BLOCKS", description: "Gestionnaire de blocs" },
      { name: "YQ_BLOCK_ADD", description: "Ajouter au bloc" },
      { name: "YQ_BLOCK_COPY", description: "Copier bloc" },
      { name: "YQ_BLOCK_LIST", description: "Lister les blocs" },
      { name: "YQ_BLOCK_REMOVE", description: "Retirer du bloc" },
      { name: "YQ_BLOCK_WRITEOUT", description: "Exporter bloc en fichier DWG" },
      { name: "YQ_BLOCK_Z0", description: "Mettre Z du bloc à 0" },
      { name: "YQ_BLOCK_BATCHRENAME", description: "Renommer blocs par lot" },
      { name: "YQ_BLOCK2BYLAYER", description: "Bloc vers ByLayer" },
      { name: "YQ_BLOCK2NEWNAME", description: "Renommer bloc" },
      { name: "YQ_BLOCKATT_LIST", description: "Lister attributs de bloc" },
      { name: "YQ_BLOCKATT2TEXT", description: "Attributs de bloc vers texte" },
      { name: "YQ_BLOCKBASEPOINT", description: "Changer point de base du bloc" },
      { name: "YQ_BLOCKBOARD", description: "Tableau de blocs" },
      { name: "YQ_BLOCKCHCOLOR", description: "Changer couleur de bloc" },
      { name: "YQ_BLOCKGROUPING", description: "Grouper blocs" },
      { name: "YQ_BLOCKSCALE", description: "Échelle de bloc" },
      { name: "YQ_BLOCKTEXT2ATT", description: "Texte de bloc vers attribut" },
      { name: "YQ_BLOCKTOOLS", description: "Outils de blocs" },
      { name: "YQ_BLOCKVIEWER", description: "Visionneuse de blocs" },
      { name: "YQ_BLOCKWIPEOUT", description: "Masquage de bloc" },
      { name: "YQ_QUICKNEWBLOCK", description: "Créer bloc rapidement" },
      { name: "YQ_QUICKDETAILBLOCK", description: "Bloc de détail rapide" },
      { name: "YQ_LINKBLOCKS", description: "Lier des blocs" },
      { name: "YQ_REPLACEBYDWG", description: "Remplacer bloc par DWG" },
      { name: "YQ_MATCH_BLOCK", description: "Copier propriétés de bloc" },
      { name: "YQ_CLEARBLK", description: "Nettoyer blocs inutilisés" },
      { name: "YQ_CREATE_MINSERT", description: "Créer MINSERT" },
      { name: "YQ_EXPLODE_MINSERT", description: "Exploser MINSERT" },
      { name: "YQ_EXPLODE_NBLOCK", description: "Exploser bloc imbriqué" },
    ],
  },

  // ─── 10. TEXT & ANNOTATIONS ───
  {
    id: "text",
    label: "Texte & Annotations / Text & Annotations",
    description: "Texte, repères, symboles et cartouches",
    commands: [
      { name: "YQ_TEXT", description: "Texte simple" },
      { name: "YQ_ETEXT", description: "Texte enrichi (multifonction)" },
      { name: "YQ_JTEXT", description: "Texte justifié" },
      { name: "YQ_DATE", description: "Insérer date automatique" },
      { name: "YQ_DRAWINGTITLE", description: "Cartouche/titre de plan" },
      { name: "YQ_LEADER", description: "Ligne de repère avec flèche" },
      { name: "YQ_LEADER_ADDARROW", description: "Ajouter flèche au repère" },
      { name: "YQ_LEADER_REVERSE", description: "Inverser repère" },
      { name: "YQ_LEADER_VERTEXES", description: "Sommets du repère" },
      { name: "YQ_LEADERALIGN", description: "Aligner repères" },
      { name: "YQ_MPTLEADER", description: "Repère multi-points" },
      { name: "YQ_MPTLEADER_Y", description: "Repère multi-points Y" },
      { name: "YQ_HBLEADER", description: "Repère horizontal" },
      { name: "YQ_INDEXER1", description: "Repère numéroté type 1" },
      { name: "YQ_INDEXER2", description: "Repère numéroté type 2" },
      { name: "YQ_INDEXER3", description: "Repère numéroté type 3" },
      { name: "YQ_INDEXER4", description: "Repère numéroté type 4" },
      { name: "YQ_INDEXER5", description: "Repère numéroté type 5" },
      { name: "YQ_INDEXER6", description: "Repère numéroté type 6" },
      { name: "YQ_INDEXER7", description: "Repère numéroté type 7" },
      { name: "YQ_INDEXER8", description: "Repère numéroté type 8" },
      { name: "YQ_INDEXER9", description: "Repère numéroté type 9" },
      { name: "YQ_INDEXERS", description: "Gestionnaire de repères" },
      { name: "YQ_IDENTIFIER1", description: "Identifiant type 1" },
      { name: "YQ_IDENTIFIER2", description: "Identifiant type 2" },
      { name: "YQ_IDENTIFIER3", description: "Identifiant type 3" },
      { name: "YQ_DETAILSYMBOL1", description: "Symbole de détail type 1" },
      { name: "YQ_DETAILSYMBOL2", description: "Symbole de détail type 2" },
      { name: "YQ_ELEVINDEXER1", description: "Repère d'élévation type 1" },
      { name: "YQ_ELEVINDEXER2", description: "Repère d'élévation type 2" },
      { name: "YQ_ELEVINDEXER3", description: "Repère d'élévation type 3" },
      { name: "YQ_ELEVINDEXER4", description: "Repère d'élévation type 4" },
      { name: "YQ_ELEVINDEXER4IN1", description: "Repère d'élévation 4-en-1" },
      { name: "YQ_COMMENTFRAME", description: "Cadre de commentaire" },
      { name: "YQ_ENTRANCEARROW", description: "Flèche d'entrée" },
      { name: "YQ_BENTARROW", description: "Flèche coudée" },
      { name: "YQ_SYMBOL_GRADIENT", description: "Symbole de pente" },
      { name: "YQ_SYMBOL_SECTIONCUTTER", description: "Symbole de coupe" },
      { name: "YQ_SYMBOL_SECTIONPLANE", description: "Plan de coupe" },
      { name: "YQ_DESIGNED_ELEVATION", description: "Cote d'élévation projet" },
      { name: "YQ_CONTOUR_ELEVATION", description: "Cote de niveau terrain" },
      { name: "YQ_INDOORELEV", description: "Cote de niveau intérieur" },
      { name: "YQ_ARCHSYMBOLS", description: "Symboles architecturaux" },
      { name: "YQ_AUTOSERIALNUMBER", description: "Numérotation auto" },
      { name: "YQ_ARRAY_NUMBERS", description: "Réseau de numéros" },
      { name: "YQ_INCREASE_NUMBERS", description: "Incrémenter numéros" },
      { name: "YQ_INCREASE_TEXT", description: "Incrémenter texte" },
      { name: "YQ_INCREASE_ATT", description: "Incrémenter attribut" },
    ],
  },

  // ─── 11. TEXT EDITING ───
  {
    id: "text_edit",
    label: "Édition de texte / Text Editing",
    description: "Modification et transformation de texte",
    commands: [
      { name: "YQ_CHANGETEXT", description: "Modifier texte" },
      { name: "YQ_TEXT_REPLACE", description: "Rechercher/remplacer texte" },
      { name: "YQ_TEXT_APPEND", description: "Ajouter texte" },
      { name: "YQ_TEXT_BREAK2", description: "Couper texte en 2" },
      { name: "YQ_TEXT_CSTYLE", description: "Style de texte courant" },
      { name: "YQ_TEXT_RESTOREMIRR", description: "Restaurer texte miroir" },
      { name: "YQ_TEXT_UPDATE", description: "Mettre à jour texte" },
      { name: "YQ_TEXT_WIDTH", description: "Largeur de texte" },
      { name: "YQ_TEXT_ALIGNMENTLEFT", description: "Aligner texte à gauche" },
      { name: "YQ_TEXT_ALIGNMENTRIGHT", description: "Aligner texte à droite" },
      { name: "YQ_TEXT2ATTDEF", description: "Texte vers définition d'attribut" },
      { name: "YQ_TEXT2CENTER", description: "Centrer texte" },
      { name: "YQ_TEXT2CLIPBOARD", description: "Texte vers presse-papier" },
      { name: "YQ_TEXT2CURVE", description: "Texte le long d'une courbe" },
      { name: "YQ_TEXTCELLAREA", description: "Aire de cellule texte" },
      { name: "YQ_TEXTCONTENT", description: "Contenu de texte" },
      { name: "YQ_TEXTOTHER", description: "Autres outils texte" },
      { name: "YQ_FINDTEXT", description: "Rechercher texte" },
      { name: "YQ_REPLACE_SUBSTRS", description: "Remplacer sous-chaînes" },
      { name: "YQ_STRCASE", description: "Changer casse" },
      { name: "YQ_DELENDSPACES", description: "Supprimer espaces en fin" },
      { name: "YQ_CHANGEATTS", description: "Modifier attributs" },
      { name: "YQ_MODIFY_ATT", description: "Modifier un attribut" },
      { name: "YQ_ERASE_BLKATT", description: "Effacer attribut de bloc" },
      { name: "YQ_DICT2TEXT", description: "Dictionnaire vers texte" },
      { name: "YQ_TXTEXP", description: "Exploser texte en géométrie" },
      { name: "YQ_REORDERTEXTS", description: "Réordonner textes" },
      { name: "YQ_UPDTEXTLIST", description: "Mettre à jour liste de textes" },
      { name: "YQ_MATCH_TEXTS", description: "Copier style de texte" },
      { name: "YQ_MATCH_TEXTHEIGHT", description: "Copier hauteur de texte" },
      { name: "YQ_MATCH_STYLE", description: "Copier style" },
      { name: "YQ_MATCH_CONTENT", description: "Copier contenu" },
      { name: "YQ_MATCH_TAGTEXT", description: "Copier tag de texte" },
      { name: "YQ_REPLACEFONTS", description: "Remplacer polices" },
      { name: "YQ_HZ_TEXT", description: "Texte horizontal" },
      { name: "YQ_HZ_EDIT", description: "Éditer texte horizontal" },
      { name: "YQ_TCH2TEXT", description: "Convertir TCH en texte" },
    ],
  },

  // ─── 12. AREA & CALCULATION ───
  {
    id: "area_calc",
    label: "Surfaces & Calculs / Area & Calculation",
    description: "Calcul de surfaces, périmètres et opérations mathématiques",
    commands: [
      { name: "YQ_AREA_PICKPT", description: "Surface par point intérieur" },
      { name: "YQ_AREASTAT", description: "Statistiques de surfaces" },
      { name: "YQ_ASSO_AREA", description: "Surface associative" },
      { name: "YQ_ASSO_PERIMETER", description: "Périmètre associatif" },
      { name: "YQ_PLINEAREA", description: "Surface de polyligne" },
      { name: "YQ_PLINEPERIMETER", description: "Périmètre de polyligne" },
      { name: "YQ_CUTAREA", description: "Surface découpée" },
      { name: "YQ_RECTANGLEAREA", description: "Surface rectangulaire" },
      { name: "YQ_CALC_ADDITION", description: "Addition" },
      { name: "YQ_CALC_SUBTRATION", description: "Soustraction" },
      { name: "YQ_CALC_MULTIPLICATION", description: "Multiplication" },
      { name: "YQ_CALC_DIVISION", description: "Division" },
      { name: "YQ_CALC_EXPRESSION", description: "Expression mathématique" },
      { name: "YQ_CALC_CELLAREA", description: "Calcul surface de cellule" },
      { name: "YQ_CALC_PERIMETER", description: "Calcul périmètre" },
      { name: "YQ_CALC_SUMAREA", description: "Somme des surfaces" },
      { name: "YQ_CALWEIGHT", description: "Calcul de poids" },
      { name: "YQ_STATISTICS", description: "Statistiques" },
      { name: "YQ_MATERIAL_LIST", description: "Liste de matériaux" },
      { name: "YQ_COORDINATE_LIST", description: "Liste de coordonnées" },
      { name: "YQ_LEN", description: "Longueur d'un objet" },
      { name: "YQ_T2PLENGTH", description: "Longueur totale de polylignes" },
    ],
  },

  // ─── 13. EDITING & MODIFY ───
  {
    id: "editing",
    label: "Édition / Editing",
    description: "Copie, déplacement, miroir, rotation, découpe avancés",
    commands: [
      { name: "YQ_DYNAMICCOPY", description: "Copie dynamique" },
      { name: "YQ_DYNAMICEXTEND", description: "Extension dynamique" },
      { name: "YQ_DYNAMICTRIM", description: "Ajustement dynamique" },
      { name: "YQ_COPY2POINTS", description: "Copier vers plusieurs points" },
      { name: "YQ_COPYANDFIX", description: "Copier et fixer (texte)" },
      { name: "YQ_COPYANDROTATE", description: "Copier et pivoter" },
      { name: "YQ_COPYDIVIDE", description: "Copier et diviser" },
      { name: "YQ_COPYSEGMENT", description: "Copier segment" },
      { name: "YQ_COPYTRANSLATE", description: "Copier et translater" },
      { name: "YQ_POLARCOPY", description: "Copie polaire/circulaire" },
      { name: "YQ_XCOPY", description: "Copie étendue" },
      { name: "YQ_MOVE_D", description: "Déplacement avec distance" },
      { name: "YQ_STRETCH_D", description: "Étirement avec distance" },
      { name: "YQ_MIRROR_EACH", description: "Miroir individuel" },
      { name: "YQ_MIRRORANDFIX", description: "Miroir et corriger texte" },
      { name: "YQ_ROTATE_EACH", description: "Rotation individuelle" },
      { name: "YQ_SCALE_EACH", description: "Échelle individuelle" },
      { name: "YQ_SCALEXYZ", description: "Échelle X/Y/Z séparée" },
      { name: "YQ_EXCHANGELOCATION", description: "Échanger positions" },
      { name: "YQ_MOVEANDFIX", description: "Déplacer et corriger" },
      { name: "YQ_EXTENDTOPOINT", description: "Étendre vers un point" },
      { name: "YQ_BATCHCHAMFER", description: "Chanfrein par lot" },
      { name: "YQ_BATCHFILLET", description: "Congé par lot" },
      { name: "YQ_BREAK_AT", description: "Casser à un point" },
      { name: "YQ_BREAK_AT2", description: "Casser à un point (variante)" },
      { name: "YQ_BREAK_EQUAL", description: "Casser en parties égales" },
      { name: "YQ_BREAK_INTERVAL", description: "Casser à intervalles" },
      { name: "YQ_BREAKALL", description: "Casser toutes intersections" },
      { name: "YQ_BREAKANDERASE", description: "Casser et effacer" },
      { name: "YQ_BREAKANDHIDDEN", description: "Casser et masquer" },
      { name: "YQ_BREAKBYKNIFE", description: "Couper par ligne" },
      { name: "YQ_BREAKBYKNIVES", description: "Couper par plusieurs lignes" },
      { name: "YQ_BREAKERASE", description: "Effacer entre deux points" },
      { name: "YQ_MERGE", description: "Fusionner objets" },
      { name: "YQ_OFFSETX", description: "Décalage étendu" },
      { name: "YQ_SELOFFSET", description: "Décalage sélectif" },
      { name: "YQ_SUPEROFFSET", description: "Super décalage" },
      { name: "YQ_SUPEREDIT", description: "Super éditeur" },
      { name: "YQ_MODIFYPLUS", description: "Modification avancée" },
      { name: "YQ_FILTERERASE", description: "Effacer par filtre" },
      { name: "YQ_ERASESURROUND", description: "Effacer autour" },
      { name: "YQ_REMOVE_DUPLICATE", description: "Supprimer doublons" },
      { name: "YQ_ORTHOGONALIZATION", description: "Orthogonaliser" },
      { name: "YQ_ALIGN2CURVE", description: "Aligner sur courbe" },
      { name: "YQ_ALIGNMENT", description: "Alignement" },
      { name: "YQ_ADJUST", description: "Ajuster" },
      { name: "YQ_TRANSFORM", description: "Transformer" },
      { name: "YQ_TRANSLATE", description: "Translater" },
    ],
  },

  // ─── 14. CURVES & POLYLINES ───
  {
    id: "curves",
    label: "Courbes & Polylignes / Curves & Polylines",
    description: "Manipulation de courbes, polylignes et conversion",
    commands: [
      { name: "YQ_2ARCPLINE", description: "Convertir en polyligne à arcs" },
      { name: "YQ_LINE2ARC", description: "Convertir ligne en arc" },
      { name: "YQ_ELLIPSE2ARC", description: "Convertir ellipse en arc" },
      { name: "YQ_SPLINE2APLINE", description: "Spline vers polyligne approx." },
      { name: "YQ_SPLINE2XPLINE", description: "Spline vers polyligne exacte" },
      { name: "YQ_PL2LWPL", description: "Polyligne vers LW polyligne" },
      { name: "YQ_PLINE_CLOSE", description: "Fermer polyligne" },
      { name: "YQ_PLINE_JOIN", description: "Joindre polylignes" },
      { name: "YQ_PLINE_OPTIMIZE", description: "Optimiser polyligne" },
      { name: "YQ_PLINE_REVERSE", description: "Inverser polyligne" },
      { name: "YQ_PLINE_VERTEXES", description: "Sommets de polyligne" },
      { name: "YQ_JOIN_ARCLINE", description: "Joindre arc et ligne" },
      { name: "YQ_LINKLINEARC", description: "Lier lignes et arcs" },
      { name: "YQ_APPENDARC", description: "Ajouter arc" },
      { name: "YQ_CURVE2BOWSTRING", description: "Courbe vers corde" },
      { name: "YQ_CURVEPROJECTION", description: "Projection de courbe" },
      { name: "YQ_CURVETOOLS", description: "Outils de courbes" },
      { name: "YQ_LINECLEAN", description: "Nettoyer lignes" },
      { name: "YQ_LINEUNION", description: "Unir lignes" },
      { name: "YQ_CONNECTVERTEXES", description: "Connecter sommets" },
      { name: "YQ_CONNECT2GLINES", description: "Connecter 2 lignes guides" },
      { name: "YQ_DIVIDESEGMENT", description: "Diviser segment" },
      { name: "YQ_2PTSDIVIDE", description: "Diviser entre 2 points" },
      { name: "YQ_ANGLEDIVIDE", description: "Division angulaire" },
      { name: "YQ_PLSEGMENT_OFFSET", description: "Décalage de segment PL" },
      { name: "YQ_PLSEGMENT_WIDTH", description: "Largeur de segment PL" },
      { name: "YQ_PLINEEXTRUDE", description: "Extruder polyligne" },
      { name: "YQ_DIAGONAL", description: "Diagonale" },
      { name: "YQ_RECT3PT", description: "Rectangle 3 points" },
      { name: "YQ_IRECTANGLE", description: "Rectangle inscrit" },
      { name: "YQ_CIRCUIT", description: "Circuit/contour fermé" },
      { name: "YQ_OUTLINE", description: "Contour extérieur" },
      { name: "YQ_OUTERHULL", description: "Enveloppe convexe" },
      { name: "YQ_INNERCONTOURS", description: "Contours intérieurs" },
      { name: "YQ_INNEROFFSET", description: "Décalage intérieur" },
      { name: "YQ_INSIDELINE", description: "Ligne intérieure" },
      { name: "YQ_BOUNDINGBOX", description: "Boîte englobante" },
      { name: "YQ_MINBOUNDINGBOX", description: "Boîte englobante minimale" },
      { name: "YQ_TOBOUNDINGBOX", description: "Convertir en boîte englobante" },
      { name: "YQ_FUZZYINSIDE", description: "Intérieur approximatif" },
      { name: "YQ_FUZZYOUTLINE", description: "Contour approximatif" },
    ],
  },

  // ─── 15. VIEWPORTS ───
  {
    id: "viewports",
    label: "Fenêtres de présentation / Viewports",
    description: "Gestion des fenêtres de présentation (Layout/Paper Space)",
    commands: [
      { name: "YQ_VIEWPORT_NEW", description: "Nouvelle fenêtre" },
      { name: "YQ_VIEWPORT_REC", description: "Fenêtre rectangulaire" },
      { name: "YQ_VIEWPORT_CEN", description: "Centrer fenêtre" },
      { name: "YQ_VIEWPORT_PAN", description: "Panoramique fenêtre" },
      { name: "YQ_VIEWPORT_SCALE", description: "Échelle de fenêtre" },
      { name: "YQ_VIEWPORT_SPLIT", description: "Diviser fenêtre" },
      { name: "YQ_VIEWPORT_SYNC", description: "Synchroniser fenêtres" },
      { name: "YQ_VIEWPORT_ISO", description: "Isoler fenêtre" },
      { name: "YQ_VIEWPORT_LOCK", description: "Verrouiller fenêtre" },
      { name: "YQ_VIEWPORT_LOCK_ALL", description: "Verrouiller toutes" },
      { name: "YQ_VIEWPORT_UNLOCK", description: "Déverrouiller fenêtre" },
      { name: "YQ_VIEWPORT_UNLOCK_ALL", description: "Déverrouiller toutes" },
      { name: "YQ_VIEWPORT_ON", description: "Activer fenêtre" },
      { name: "YQ_VIEWPORT_ON_ALL", description: "Activer toutes" },
      { name: "YQ_VIEWPORT_OFF", description: "Désactiver fenêtre" },
      { name: "YQ_VIEWPORT_OFF_ALL", description: "Désactiver toutes" },
      { name: "YQ_VIEWPORT2PSPACE", description: "Fenêtre vers Paper Space" },
      { name: "YQ_VIEWPORTTOOLS", description: "Outils de fenêtres" },
      { name: "YQ_CURVE2VIEWPORT", description: "Courbe vers fenêtre" },
      { name: "YQ_MODEL2VIEWPORT", description: "Model vers fenêtre" },
      { name: "YQ_SCALEVPS", description: "Échelle de toutes les fenêtres" },
      { name: "YQ_VPLAYER_FREEZE", description: "Geler calque dans fenêtre" },
      { name: "YQ_VPLAYER_THAW", description: "Dégeler calque dans fenêtre" },
      { name: "YQ_VPLAYER_GRAY", description: "Griser calque dans fenêtre" },
      { name: "YQ_VPLAYER_ISO", description: "Isoler calque dans fenêtre" },
      { name: "YQ_VPLAYER_ISOALL", description: "Isoler dans toutes fenêtres" },
      { name: "YQ_VPLAYER_NFREEZE", description: "Geler (non-courant) dans fenêtre" },
      { name: "YQ_VPLAYER_RECOVER", description: "Récupérer calque dans fenêtre" },
      { name: "YQ_VPLAYER_MANAGER", description: "Gestionnaire de calques VP" },
      { name: "YQ_VPLAYER2RECOVER", description: "Récupérer calques VP" },
    ],
  },

  // ─── 16. INTERIOR & DECORATION ───
  {
    id: "interior",
    label: "Intérieur & Décoration / Interior",
    description: "Mobilier, éclairage, cuisine, décoration intérieure",
    commands: [
      { name: "YQ_DECORATION", description: "Décoration intérieure" },
      { name: "YQ_AUTOFURNITURE", description: "Mobilier automatique" },
      { name: "YQ_AUTOLAMPS", description: "Éclairage automatique" },
      { name: "YQ_CHESTPLAN", description: "Plan de meuble/commode" },
      { name: "YQ_CUPBOARDELEV", description: "Élévation de placard" },
      { name: "YQ_CUPBOARDPLAN", description: "Plan de placard" },
      { name: "YQ_LANDSCAPE", description: "Aménagement paysager" },
      { name: "YQ_LIGHTTROUGH", description: "Gorge lumineuse" },
      { name: "YQ_SAWTOOTH", description: "Dents de scie (toiture)" },
      { name: "YQ_BEGONIA", description: "Motif bégonia" },
      { name: "YQ_HEAPTREES", description: "Arbres groupés" },
      { name: "YQ_RANDOMSPREAD", description: "Distribution aléatoire" },
    ],
  },

  // ─── 17. DRAWING & EXPORT ───
  {
    id: "drawing_export",
    label: "Dessin & Export / Drawing & Export",
    description: "Impression, export, comparaison de plans",
    commands: [
      { name: "YQ_BATCHPLOT", description: "Impression par lot" },
      { name: "YQ_DWGFRAME", description: "Cadre de dessin" },
      { name: "YQ_FRAMES2LAYOUTS", description: "Cadres vers présentations" },
      { name: "YQ_OUTPUTDWGS", description: "Exporter fichiers DWG" },
      { name: "YQ_OUTPUTDWGS3", description: "Export DWG (variante 3)" },
      { name: "YQ_OUTPUTLAYERS", description: "Exporter calques" },
      { name: "YQ_ARRANGEDWGS", description: "Arranger fichiers DWG" },
      { name: "YQ_COMPAREDWGS", description: "Comparer fichiers DWG" },
      { name: "YQ_SNAPSHOT", description: "Capture d'écran" },
      { name: "YQ_DRAWCLIPBOARD", description: "Presse-papier dessin" },
      { name: "YQ_PICKAREA2EXCEL", description: "Surface vers Excel" },
      { name: "YQ_TEXTS2EXCEL", description: "Textes vers Excel" },
      { name: "YQ_EXCEL2TABLE", description: "Excel vers tableau AutoCAD" },
      { name: "YQ_TEXTS2ACADTABLE", description: "Textes vers tableau AutoCAD" },
      { name: "YQ_ACAD2KML", description: "AutoCAD vers Google Earth (KML)" },
      { name: "YQ_GEODESIC_COORDINATES", description: "Coordonnées géodésiques" },
      { name: "YQ_EMPTYTABLE", description: "Tableau vide" },
      { name: "YQ_TRIMTABLE", description: "Ajuster tableau" },
      { name: "YQ_FRAMEDIVIDED", description: "Cadre divisé" },
      { name: "YQ_SETDWGSCALE", description: "Définir échelle du dessin" },
    ],
  },

  // ─── 18. MATCH & PROPERTIES ───
  {
    id: "match_properties",
    label: "Propriétés & Correspondance / Match Properties",
    description: "Copie de propriétés entre objets et conversion de couleurs",
    commands: [
      { name: "YQ_MATCHBRUSH", description: "Pinceau de correspondance" },
      { name: "YQ_MATCH_COLOR", description: "Copier couleur" },
      { name: "YQ_MATCH_LAYER", description: "Copier calque" },
      { name: "YQ_MATCH_LAYERCOLOR", description: "Copier couleur de calque" },
      { name: "YQ_MATCH_LINETYPE", description: "Copier type de ligne" },
      { name: "YQ_MATCH_ROTATION", description: "Copier rotation" },
      { name: "YQ_MATCH_THICKNESS", description: "Copier épaisseur" },
      { name: "YQ_MATCH_WIDTH", description: "Copier largeur" },
      { name: "YQ_MATCH_DYNPROPS", description: "Copier propriétés dynamiques" },
      { name: "YQ_MATCH_VPLAYER", description: "Copier calque de fenêtre" },
      { name: "YQ_2BYLAYER", description: "Propriétés vers ByLayer" },
      { name: "YQ_2GRAY", description: "Convertir en gris" },
      { name: "YQ_2LAYERCOLOR", description: "Couleur vers couleur de calque" },
      { name: "YQ_ALL2GRAY", description: "Tout convertir en gris" },
      { name: "YQ_COLORFILTER", description: "Filtre par couleur" },
      { name: "YQ_COLORKEYS", description: "Raccourcis couleurs" },
      { name: "YQ_CHECKCOLOR", description: "Vérifier couleurs" },
      { name: "YQ_LOADLINETYPE", description: "Charger type de ligne" },
      { name: "YQ_LTSCALE", description: "Échelle de type de ligne" },
      { name: "YQ_LTSWITCH", description: "Basculer type de ligne" },
      { name: "YQ_LTYPEKEYS", description: "Raccourcis types de lignes" },
      { name: "YQ_MKLINETYPE", description: "Créer type de ligne" },
      { name: "YQ_PUTLTSCALE", description: "Appliquer échelle de ligne" },
    ],
  },

  // ─── 19. CONSTRUCTION & STEEL ───
  {
    id: "construction",
    label: "Construction & Acier / Construction & Steel",
    description: "Profilés acier, tuyauterie, soudure, quincaillerie",
    commands: [
      { name: "YQ_FORMEDSTEEL", description: "Profilé acier" },
      { name: "YQ_IRONFRAME", description: "Cadre métallique" },
      { name: "YQ_WOODENFRAME", description: "Cadre bois" },
      { name: "YQ_PIPE", description: "Tuyau" },
      { name: "YQ_PIPECUTTING", description: "Découpe de tuyau" },
      { name: "YQ_HOSE", description: "Tuyau flexible" },
      { name: "YQ_WELDINGLINE", description: "Ligne de soudure" },
      { name: "YQ_BACKBOLTHOLE", description: "Trou de boulon arrière" },
      { name: "YQ_BOARDHOLE", description: "Trou dans panneau" },
      { name: "YQ_BOARDSPLIT", description: "Découpe de panneau" },
      { name: "YQ_ARRAY_BOARDS", description: "Réseau de panneaux" },
      { name: "YQ_COMPONENTS", description: "Composants" },
      { name: "YQ_HEELBLOCK", description: "Bloc de talon" },
      { name: "YQ_DISCONNECTION_LINE", description: "Ligne de déconnexion" },
      { name: "YQ_REVCLOUD", description: "Nuage de révision" },
      { name: "YQ_WIRESURROUND", description: "Entourage fil" },
    ],
  },

  // ─── 20. GROUPS ───
  {
    id: "groups",
    label: "Groupes / Groups",
    description: "Gestion des groupes d'objets",
    commands: [
      { name: "YQ_GROUP_ADD", description: "Ajouter au groupe" },
      { name: "YQ_GROUP_REMOVE", description: "Retirer du groupe" },
      { name: "YQ_GROUP_SEPARATE", description: "Séparer le groupe" },
      { name: "YQ_EXPLODEGROUP", description: "Exploser groupe" },
      { name: "YQ_QUICKGROUP", description: "Groupe rapide" },
      { name: "YQ_PURGEGROUP", description: "Purger groupes vides" },
    ],
  },

  // ─── 21. SYSTEM & SETTINGS ───
  {
    id: "system",
    label: "Système & Paramètres / System & Settings",
    description: "System settings, units, system variables",
    commands: [
      { name: "YQ_SYS_SETTING", description: "Paramètres système YQ" },
      { name: "YQ_SYSTEMSETUP", description: "Configuration système" },
      { name: "YQ_SETUNITS", description: "Définir unités" },
      { name: "YQ_SETUSER", description: "Définir utilisateur" },
      { name: "YQ_OSMODE", description: "Mode d'accrochage" },
      { name: "YQ_BGCOLOR", description: "Couleur d'arrière-plan" },
      { name: "YQ_COMMANDFINDER", description: "Chercher une commande" },
      { name: "YQ_COMMANDPANEL", description: "Panneau de commandes" },
      { name: "YQ_FUNCTIONFINDER", description: "Chercher une fonction" },
      { name: "YQ_SOURCEFINDER", description: "Chercher la source" },
      { name: "YQ_MENU", description: "Main menu" },
      { name: "YQ_SLIDEMENU", description: "Menu déroulant" },
      { name: "YQ_EXTRATOOLS", description: "Outils supplémentaires" },
      { name: "YQ_OTHERTOOLS", description: "Autres outils" },
      { name: "YQ_VER", description: "Plugin version" },
      { name: "YQ_ABOUT", description: "About plugin" },
      { name: "YQ_HELP", description: "Help" },
      { name: "YQ_LANG", description: "Langue" },
      { name: "YQ_REPAIR", description: "Réparer dessin" },
      { name: "YQ_PURGEALL", description: "Purger tout" },
      { name: "YQ_PURGEFILES", description: "Purger fichiers" },
      { name: "YQ_PURGEOBJDICT", description: "Purger dictionnaire objets" },
      { name: "YQ_CHECKCORRECT", description: "Vérifier et corriger" },
      { name: "YQ_CLEAR_Z", description: "Remettre Z à 0" },
      { name: "YQ_CLEARALLRA", description: "Nettoyer tous les réacteurs" },
      { name: "YQ_FINDNONORTHOLINES", description: "Trouver lignes non-orthogonales" },
      { name: "YQ_CHKCLOSED", description: "Vérifier fermeture" },
      { name: "YQ_DISPLAYALL", description: "Afficher tout" },
      { name: "YQ_DISPLAYHIDE", description: "Masquer sélection" },
      { name: "YQ_HIDESELECT", description: "Masquer objets sélectionnés" },
      { name: "YQ_HIDEUNSELECT", description: "Masquer objets non-sélectionnés" },
      { name: "YQ_NORMAL", description: "Vue normale" },
      { name: "YQ_OVERTURN", description: "Retourner" },
      { name: "YQ_TOOLBARSON", description: "Afficher barres d'outils" },
      { name: "YQ_TOOLBARSOFF", description: "Masquer barres d'outils" },
      { name: "YQ_UCSBBOX", description: "UCS par boîte englobante" },
      { name: "YQ_UCSDIR", description: "Direction UCS" },
      { name: "YQ_UCSMATCH", description: "Correspondre UCS" },
      { name: "YQ_XREF2ABS", description: "Xref chemin absolu" },
      { name: "YQ_XREF2REL", description: "Xref chemin relatif" },
      { name: "YQ_HYPERLINK", description: "Hyperlien" },
      { name: "YQ_USERDICT", description: "Dictionnaire utilisateur" },
      { name: "YQ_OPENTIME", description: "Temps d'ouverture" },
      { name: "YQ_EXPLODABLE", description: "Rendre explosable" },
      { name: "YQ_NONEXPLODABLE", description: "Rendre non-explosable" },
      { name: "YQ_QUICKWIPEOUT", description: "Masquage rapide" },
      { name: "YQ_SWITCH_DYNAMIC", description: "Basculer propriétés dynamiques" },
    ],
  },

  // ─── 22. MISC UTILITIES ───
  {
    id: "misc",
    label: "Utilitaires divers / Miscellaneous",
    description: "Commandes spécialisées et utilitaires variés",
    commands: [
      { name: "YQ_00", description: "Couleur/type/épaisseur vers ByLayer" },
      { name: "YQ_MI", description: "Miroir avancé" },
      { name: "YQ_CM", description: "Copie multiple" },
      { name: "YQ_RZ", description: "Rotation vers 0°" },
      { name: "YQ_RG", description: "Régénérer sélection" },
      { name: "YQ_ZD", description: "Zoom 0.5x" },
      { name: "YQ_ZE", description: "Zoom étendu" },
      { name: "YQ_ZZ", description: "Zoom précédent" },
      { name: "YQ_EDB", description: "Exploser bloc vers calque d'origine" },
      { name: "YQ_EDC", description: "Exploser bloc vers calque courant" },
      { name: "YQ_CCB", description: "Copier base et effacer" },
      { name: "YQ_A2C", description: "Arc vers cercle" },
      { name: "YQ_C2X", description: "Cercle vers donut" },
      { name: "YQ_C2VV", description: "Cercle vers VV" },
      { name: "YQ_S2A", description: "SOLID vers area" },
      { name: "YQ_S2X", description: "Spline vers polyligne" },
      { name: "YQ_AS2R", description: "Arc/spline vers rectangle" },
      { name: "YQ_VXX", description: "Déplacement par sélection" },
      { name: "YQ_CXX", description: "Copie par sélection" },
      { name: "YQ_FXX", description: "Congé polyligne" },
      { name: "YQ_CFXX", description: "Chanfrein polyligne" },
      { name: "YQ_QGTX", description: "Découpage d'image par contour" },
      { name: "YQ_REFX", description: "Exploser référence externe" },
      { name: "YQ_EXPATTBLK", description: "Exploser bloc attribut" },
      { name: "YQ_IMAGESPLIT", description: "Découper image" },
      { name: "YQ_CYLINDERSHADOW", description: "Ombre cylindrique" },
      { name: "YQ_TOFREEHAND", description: "Convertir en main levée" },
      { name: "YQ_ENAMEFILTER", description: "Filtre par nom d'entité" },
      { name: "YQ_PICKRECT", description: "Sélection rectangulaire" },
      { name: "YQ_COPY_MEMORIAL", description: "Copier mémorial" },
      { name: "YQ_MOVE_MEMORIAL", description: "Déplacer mémorial" },
      { name: "YQ_NUMBERLINES", description: "Numéroter lignes" },
      { name: "YQ_PASTEDETAILDWG", description: "Coller détail DWG" },
      { name: "YQ_RECTANGLEMIDLINE", description: "Ligne médiane rectangle" },
      { name: "YQ_OBLIQUE_CORRECTION", description: "Correction oblique" },
      { name: "YQ_ALIGNFRAME", description: "Aligner cadre" },
      { name: "YQ_STRING_LIST", description: "Liste de chaînes" },
      { name: "YQ_WPLINE2WIREFRAME", description: "WPolyligne vers fil de fer" },
      { name: "YQ_APPENDDIM2CELL", description: "Ajouter cote à cellule" },
      { name: "YQ_APPENDNUM2CELL", description: "Ajouter numéro à cellule" },
      { name: "YQ_APPENDTEXT2CELL", description: "Ajouter texte à cellule" },
      { name: "YQ_CATALOG", description: "Catalogue" },
      { name: "YQ_WIN", description: "Fenêtrage/sélection par fenêtre" },
      { name: "YQ_LASTYQCMD", description: "Dernière commande YQ" },
      { name: "YQ_SLDCOMPONENTS", description: "Composants menu déroulant" },
      { name: "YQ_SLDDECORATION", description: "Décoration menu déroulant" },
      { name: "YQ_SLDINDEXERS", description: "Repères menu déroulant" },
      { name: "YQ_SLDSTATISTICS", description: "Statistiques menu déroulant" },
      { name: "YQ_SLDSTYLES", description: "Styles menu déroulant" },
      { name: "YQ_SLDSYMBOLS", description: "Symboles menu déroulant" },
      { name: "YQ_HBEDIT", description: "Éditer bloc de base" },
      { name: "YQ_ARRANGEWC", description: "Arranger WC/sanitaires" },
      { name: "YQ_BLOCKVIEWER1", description: "Visionneuse blocs 1" },
      { name: "YQ_BLOCKVIEWER2", description: "Visionneuse blocs 2" },
      { name: "YQ_BLOCKVIEWER3", description: "Visionneuse blocs 3" },
      { name: "YQ_BLOCKVIEWER4", description: "Visionneuse blocs 4" },
      { name: "YQ_BLOCKVIEWER5", description: "Visionneuse blocs 5" },
      { name: "YQ_BLOCKVIEWER6", description: "Visionneuse blocs 6" },
      { name: "YQ_BLOCKVIEWER7", description: "Visionneuse blocs 7" },
      { name: "YQ_BLOCKVIEWER8", description: "Visionneuse blocs 8" },
      { name: "YQ_BLOCKVIEWER9", description: "Visionneuse blocs 9" },
      { name: "YQ_LT0", description: "Échelle ligne 0" },
      { name: "YQ_LT10", description: "Échelle ligne 10" },
      { name: "YQ_LT1000", description: "Échelle ligne 1000" },
      { name: "YQ_PGP2LSP", description: "Convertir PGP en LSP" },
      { name: "YQ_RELSWITCH", description: "Basculer mode relatif" },
      { name: "YQ_DONATE", description: "Faire un don" },
      { name: "YQ_CHKYQVER", description: "Vérifier version YQ" },
      { name: "YQ_CLEARRANOUSE", description: "Nettoyer entrées non utilisées" },
      { name: "YQ_LMZK", description: "Raccourci LMZK" },
      { name: "YQ_LSXQ", description: "Raccourci LSXQ" },
      { name: "YQ_CBJ", description: "Raccourci CBJ" },
      { name: "YQ_KC", description: "Raccourci KC" },
      { name: "YQ_JYB", description: "Raccourci JYB" },
      { name: "YQ_NYS", description: "Raccourci NYS" },
      { name: "YQ_QZX", description: "Raccourci QZX" },
      { name: "YQ_ZCX", description: "Raccourci ZCX" },
      { name: "YQ_HHS", description: "Raccourci HHS" },
      { name: "YQ_YDFY", description: "Raccourci YDFY" },
      { name: "YQ_EL2C", description: "Ellipse vers cercle" },
      { name: "YQ_TZCRACKER", description: "Outil TZ" },
      { name: "YQ", description: "Main command menu" },
      { name: "YQABOUT", description: "À propos" },
      { name: "YQARCH", description: "Launch plugin" },
      { name: "YQHELP", description: "Aide" },
      { name: "YQJZ", description: "Raccourci YQJZ" },
      { name: "YQLANG", description: "Langue YQ" },
      { name: "YQMENU", description: "Menu YQ" },
      { name: "YQSYS", description: "Système YQ" },
      { name: "YQUNINST", description: "Désinstaller YQ" },
      { name: "YQUNITS", description: "Unités YQ" },
      { name: "YQUSER", description: "Utilisateur YQ" },
      { name: "YQVER", description: "Version YQ" },
      { name: "YQWEB", description: "Site web YQ" },
      { name: "YQ_2MU", description: "Convertir en unités multiples" },
      { name: "YQ_CZZ", description: "Raccourci CZZ" },
      { name: "YQ_ENTLIST2", description: "Liste entités type 2" },
      { name: "YQ_ENTLIST3", description: "Liste entités type 3" },
      { name: "YQ_FORUM", description: "Community forum" },
      { name: "YQ_TRIMTHRUMS", description: "Ajuster extrémités" },
      { name: "YQ_UNINSTALL", description: "Uninstall plugin" },
      { name: "YQ_VZZ", description: "Raccourci VZZ" },
      { name: "YQ_WEBSITE", description: "Plugin website" },
    ],
  },
];

/** Flat lookup: command name → category id */
export const commandIndex = new Map<string, string>();
for (const cat of categories) {
  for (const cmd of cat.commands) {
    commandIndex.set(cmd.name, cat.id);
  }
}

/** All valid command names */
export const allCommandNames = new Set<string>(commandIndex.keys());
